Add ARCx Governance Token
snapshot-labs/snapshot-spaces pull request #1008
Opened 2021-03-21 04:48 UTC by kermankohli

#### Hi! What is your PR about?

- [x] Add images for your space
- [X] Add custom domain for your space
- [X] Add alias for migrate your space
- [X] Add or edit a skin

2021-03-22 01:53 UTC, gokaiorg requested changes
- Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.
- The images file size should not exceed 50KB. Please reduce their weight.

2021-03-24 12:16 UTC, kermankohli commented
Done, let us know if there's anything else :)

2021-03-25 01:22 UTC, gokaiorg requested changes
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/arcx.eth

2021-03-25 01:22 UTC, gokaiorg commented on spaces/arcx.eth/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-03-25 01:22 UTC, gokaiorg commented on skins/arcx.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/112404601-39624980-8d43-11eb-9335-e83250ccf2b2.png)

2021-03-25 03:26 UTC, kermankohli commented
Realised that the way of creating things on Snapshot has changed, used the UI instead and this PR just contains the logos and an entry to the domains list :)

2021-03-25 03:31 UTC, gokaiorg approved these changes

2021-03-25 03:32 UTC, merged