Add MACARONSWAP space
snapshot-labs/snapshot-spaces pull request #1034
Opened 2021-03-28 12:14 UTC by macaronchef

#### Hi! What is your PR about?

- [x] Add images for your space
- [x ] Add custom domain for your space
- [ x] Add alias for migrate your space
- [ x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-28 12:52 UTC, mantorra commented
Hi, It's BSC project, does it require to get ENS again?

2021-03-28 23:29 UTC, gokaiorg requested changes
Your space name directory should be similar to your ENS. Follow this example `spaces/macaronswap.eth/logo.png`.

2021-03-28 23:29 UTC, gokaiorg commented on skins/macaronswap.scss
> +.pancake {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.macaronswap {
```

2021-03-28 23:29 UTC, gokaiorg commented on spaces/macaronswap/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-03-28 23:29 UTC, gokaiorg commented on spaces/spotlight.json
>  ]
Please do not edit the spotlight file, no editing is allowed. Thank you.

2021-03-29 00:08 UTC, macaronchef commented
I fixed all issues about PR, Please merge it thanks.

2021-03-29 00:56 UTC, gokaiorg requested changes

2021-03-29 00:56 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.macaronswap.finance": "macaronswap"
Your space domain selector should be similar to your ENS.
```suggestion
  "vote.macaronswap.finance": "macaronswap.eth"
```

2021-03-29 09:55 UTC, macaronchef commented
Changes commited. Thanks

2021-03-29 10:46 UTC, gokaiorg approved these changes

2021-03-29 10:49 UTC, merged