Add Space suni.eth
snapshot-labs/snapshot-spaces pull request #1035
Opened 2021-03-28 22:41 UTC by edinsoncs

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-28 23:31 UTC, gokaiorg requested changes

2021-03-28 23:31 UTC, gokaiorg commented on spaces/suni.eth/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-03-29 07:51 UTC, edinsoncs commented on spaces/suni.eth/index.json
> +}
The index.json file was successfully deleted

2021-03-29 08:36 UTC, gokaiorg approved these changes

2021-03-29 08:36 UTC, merged