add images and domain
snapshot-labs/snapshot-spaces pull request #1039
Opened 2021-03-29 21:50 UTC by iulianivg

#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-30 01:33 UTC, gokaiorg requested changes

2021-03-30 01:33 UTC, gokaiorg commented on spaces/resdx.eth/domains.json
> +}
You will need to add your sub domain in this file https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json and delete the `domains.json` created in your space.

2021-03-30 08:30 UTC, iulianivg commented on spaces/resdx.eth/domains.json
> +}
oops. fixed

2021-03-31 00:31 UTC, gokaiorg approved these changes

2021-03-31 00:44 UTC, merged