add pepemon custom domain
snapshot-labs/snapshot-spaces pull request #1041
Opened 2021-03-30 11:28 UTC by pepem00n

#### Hi! What is your PR about?

- [] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-30 11:56 UTC, gokaiorg requested changes

2021-03-30 11:56 UTC, gokaiorg commented on spaces/domains.json
>    "vote.macaronswap.finance": "macaronswap.eth"
You will miss a comma at the end of the line above your sub domain.
```suggestion
  "vote.macaronswap.finance": "macaronswap.eth",
```

2021-04-04 00:46 UTC, alexppmax approved these changes
fixed

2021-04-04 01:04 UTC, gokaiorg requested changes
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-04-04 01:11 UTC, alexppmax approved these changes

2021-04-04 01:53 UTC, closed without merging