B.Protocol
snapshot-labs/snapshot-spaces pull request #1052
Opened 2021-04-01 12:51 UTC by yaronvel

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [x] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-02 01:32 UTC, gokaiorg requested changes

2021-04-02 01:32 UTC, gokaiorg commented on spaces/aliases.json
> +  "cBProtocol" : "bsnapshot.eth"
When creating a space you do not have to edit the `aliases.json` file.
```suggestion
  "macaronswap": "macaronswap.eth"
```

2021-04-04 09:54 UTC, yaronvel commented on spaces/aliases.json
> +  "cBProtocol" : "bsnapshot.eth"
But we want to add two aliases, one for mbprotocol and one for cbprotocol

2021-04-04 15:40 UTC, gokaiorg requested changes
Images looks good to me!

2021-04-04 15:40 UTC, gokaiorg commented on spaces/aliases.json
> +  "cBProtocol" : "bsnapshot.eth"
You have to create an alias if you had a space that was created before the implementation of ENS and I can't find https://snapshot.org/#/mbprotocol and https://snapshot.org/#/cbprotocol. You are rather on a space creation and you don't need an alias

2021-04-04 15:40 UTC, gokaiorg commented on spaces/aliases.json
> +  "cBProtocol" : "bsnapshot.eth"
Maybe you want to make a subdomain? https://docs.snapshot.org/spaces/add-custom-domain

2021-04-04 16:04 UTC, yaronvel commented on spaces/aliases.json
> +  "cBProtocol" : "bsnapshot.eth"
oh, i think i misunderstood the feature.
We want it to be hosted on snapshot.org, however we don't want it to include `.eth` and potentially other characters as well.
E.g., like `https://snapshot.org/#/dai` doesn't have `.eth`.
Are you saying this is no longer possible?
If it isn't, then we will use our own custom domain.

2021-04-04 16:11 UTC, gokaiorg commented on spaces/aliases.json
> +  "cBProtocol" : "bsnapshot.eth"
> Are you saying this is no longer possible?
Yes, now the spaces are created with ENS and have the domain extension .eth or .xyz. The solution is to create your own subdomain.

2021-04-04 16:11 UTC, yaronvel commented on spaces/aliases.json
> +  "cBProtocol" : "bsnapshot.eth"
I submitted a fix that will only use a domain.
Sorry for the confusion.

2021-04-04 16:18 UTC, gokaiorg commented
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-04-04 16:43 UTC, yaronvel commented
> There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

done

2021-04-05 15:10 UTC, gokaiorg commented
@yaronvel There is still conflict in your RP. You need to update your local before you start committing again.

2021-04-05 15:46 UTC, yaronvel commented
> @yaronvel There is still conflict in your RP. You need to update your local before you start committing again.

i keep resolving conflicts but then new projects are being merged before my PR.
Updated again.
Please merge my PR before others :)

2021-04-06 01:33 UTC, gokaiorg approved these changes

2021-04-06 01:34 UTC, merged