Fei Protocol Snapshot
snapshot-labs/snapshot-spaces pull request #1056
Opened 2021-04-02 03:22 UTC by Joeysantoro

#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-02 03:27 UTC, gokaiorg requested changes

2021-04-02 03:27 UTC, gokaiorg commented on skins/fei.scss
> +.my-space {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.fei {
```

2021-04-02 04:07 UTC, sebastiandelgado commented
@gokaiorg Thanks for the suggestion. I just committed it. Just wanted to check that its ok, for the scss file and the css selector to be named `fei` while our directory under `/spaces` is named `/spaces/fei.eth`

2021-04-07 01:25 UTC, gokaiorg requested changes
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-04-10 00:45 UTC, sebastiandelgado commented
@gokaiorg just fixed the merge conflict!

2021-04-10 01:31 UTC, gokaiorg approved these changes

2021-04-10 01:31 UTC, merged