add iftip.eth
snapshot-labs/snapshot-spaces pull request #1078
Opened 2021-04-08 08:50 UTC by bibodeng

#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-08 09:23 UTC, gokaiorg requested changes

2021-04-08 09:23 UTC, gokaiorg commented on spaces/iftip.eth/domains.json
> +}
- You have to add your subdomain in the list of the file https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json
- You should not add domains.json files in your space, please delete it.

2021-04-08 09:27 UTC, bibodeng commented on spaces/iftip.eth/domains.json
> +}
OK, I've done this in new fix update

2021-04-10 01:43 UTC, gokaiorg commented
To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

2021-04-12 07:58 UTC, bibodeng commented
@gokaiorg Hi, I fix the conflict, you can go ahead

2021-04-12 08:58 UTC, gokaiorg approved these changes

2021-04-12 08:59 UTC, merged