add logo for strudel.eth space
snapshot-labs/snapshot-spaces pull request #1079
Opened 2021-04-08 09:31 UTC by johannbarbie

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-08 12:40 UTC, gokaiorg requested changes

2021-04-08 12:40 UTC, gokaiorg commented on spaces/strudel.eth/domains.json
> +}
- You need to add your subdomain in the list of the file https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json
- You should not add domains.json files in your space, please delete it.

2021-04-08 13:43 UTC, johannbarbie commented on spaces/strudel.eth/domains.json
> +}
thx, will fix that

2021-04-08 13:46 UTC, johannbarbie commented
@gokaiorg i've addressed your comment. how to continue, will you reevaluate, or should i open a new PR?

2021-04-09 11:08 UTC, johannbarbie commented
@gokaiorg ping :)

2021-04-10 01:32 UTC, gokaiorg approved these changes

2021-04-10 01:32 UTC, merged