Supra Finance Addition
snapshot-labs/snapshot-spaces pull request #1085
Opened 2021-04-09 22:42 UTC by MarcoLPR

#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-10 01:39 UTC, gokaiorg requested changes
Your space name directory should be similar to your ENS. Follow this example `spaces/suprafinance.xyz/logo.png`.
https://snapshot.org/#/suprafinance.xyz

2021-04-10 01:39 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.supra.finance": "suprafinance"
Your domain field value should be similar to your space directory `"my.custom.domain": "my-space.eth"`.
```suggestion
  "vote.supra.finance": "suprafinance.xyz"
```

2021-04-10 01:39 UTC, gokaiorg commented on spaces/suprafinance/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-04-10 01:39 UTC, gokaiorg commented
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-04-11 17:32 UTC, MarcoLPR commented
Ready @gokaiorg 

Thanks for the comments!

2021-04-12 02:53 UTC, gokaiorg approved these changes

2021-04-12 02:54 UTC, merged