Added HaloDAO
snapshot-labs/snapshot-spaces pull request #1092
Opened 2021-04-13 08:14 UTC by mystbrent

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-13 09:50 UTC, gokaiorg requested changes
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

2021-04-13 09:50 UTC, gokaiorg commented on spaces/halodao/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-04-13 11:55 UTC, mystbrent commented on spaces/halodao/index.json
> +}
Got it removed the index.json in the latest commit. Thank you

2021-04-14 04:38 UTC, gokaiorg requested changes
Your space name directory should be similar to your ENS. Follow this example `spaces/halodao.eth/logo.png`.

2021-04-14 07:34 UTC, mystbrent commented
> Your space name directory should be similar to your ENS. Follow this example `spaces/halodao.eth/logo.png`.

Got it. It has been resolved in the latest commit. Thank you

2021-04-14 08:07 UTC, gokaiorg approved these changes

2021-04-14 08:07 UTC, merged