added index.json and updated domains.json
snapshot-labs/snapshot-spaces pull request #1108
Opened 2021-04-15 12:03 UTC by weechien

#### Hi! What is your PR about?

- [] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-16 00:43 UTC, gokaiorg requested changes

2021-04-16 00:43 UTC, gokaiorg commented on spaces/parallaxprotocol.eth/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-04-16 00:43 UTC, gokaiorg commented on spaces/domains.json
>  }
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-04-16 14:35 UTC, weechien commented on spaces/parallaxprotocol.eth/index.json
> +}
I have removed the request file and folder, thank you.

2021-04-16 15:26 UTC, weechien commented on spaces/domains.json
>  }
Hi, I have pulled the latest `domains.json` and updated accordingly, thank you.

2021-04-17 03:42 UTC, gokaiorg approved these changes

2021-04-17 03:42 UTC, merged