Update domains.json
snapshot-labs/snapshot-spaces pull request #1124
Opened 2021-04-20 08:22 UTC by tzhan28

#### Hi! What is your PR about?

Add custom domain for your space

2021-04-20 10:00 UTC, gokaiorg requested changes

2021-04-20 10:00 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.mask.io": "tianranzhang.eth"
A comma is missing at the end of the line above your sub-domain.
```suggestion
  "vote.nerve.fi": "nervefinance.eth",
  "vote.mask.io": "tianranzhang.eth"
```

2021-04-20 10:03 UTC, tzhan28 reviewed
Thx for catching!

2021-04-21 01:53 UTC, gokaiorg approved these changes

2021-04-21 01:53 UTC, merged