add Based Loans signage
snapshot-labs/snapshot-spaces pull request #1155
Opened 2021-04-27 17:42 UTC by kernelwildfire

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-28 02:17 UTC, gokaiorg requested changes

2021-04-28 02:17 UTC, gokaiorg commented on skins/basedloans.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/116336344-93eb3b80-a802-11eb-8da6-63d09cdd1663.png)

2021-04-28 16:57 UTC, kernelwildfire commented
changed color

2021-04-29 01:49 UTC, gokaiorg approved these changes

2021-04-29 01:49 UTC, merged