Add libertas.eth
snapshot-labs/snapshot-spaces pull request #1160
Opened 2021-04-28 14:17 UTC by TheLibertasProject

#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-29 01:54 UTC, gokaiorg requested changes
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-04-29 01:54 UTC, gokaiorg commented on skins/uniswap.scss
> +// dark theme
Please remove this comment. 
```suggestion
```

2021-04-29 11:51 UTC, TheLibertasProject commented
I will resubmit a new one. Domains.json is still incorrect.

2021-04-29 16:35 UTC, TheLibertasProject commented on skins/uniswap.scss
> +// dark theme
Done

2021-04-30 04:02 UTC, gokaiorg approved these changes

2021-04-30 04:02 UTC, merged