Add treatvote.eth
snapshot-labs/snapshot-spaces pull request #1164
Opened 2021-04-28 20:10 UTC by tangent10

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-29 02:01 UTC, gokaiorg requested changes

2021-04-29 02:01 UTC, gokaiorg commented on skins/treat.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/116493676-687f5400-a8c9-11eb-80fe-52db2397cb55.png)

2021-04-29 22:13 UTC, tangent10 commented on skins/treat.scss
> +}
whoops, missed that. thanks for the review. i've removed the skin.

2021-05-01 03:10 UTC, gokaiorg approved these changes

2021-05-01 03:10 UTC, merged