Add Halodao skin
snapshot-labs/snapshot-spaces pull request #1166
Opened 2021-04-29 11:08 UTC by mystbrent

#### Hi! What is your PR about?

- [ ] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-04-30 04:17 UTC, gokaiorg requested changes

2021-04-30 04:17 UTC, gokaiorg commented on skins/halodao.scss
> +  }
Please use only theme variables. No extra custom styles are allowed except on #topnav.
```suggestion
```

2021-04-30 08:38 UTC, mystbrent commented on skins/halodao.scss
> +  }
I see copy that

2021-04-30 08:39 UTC, mystbrent commented
Custom styles are removed on the latest commit changes

2021-04-30 08:47 UTC, gokaiorg requested changes

2021-04-30 08:47 UTC, gokaiorg commented on skins/halodao.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/116671558-45d56400-a9cb-11eb-8eba-8a8d523ee05e.png)

2021-05-14 07:33 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-05-14 07:33 UTC, closed without merging

2021-05-19 13:03 UTC, mystbrent commented
Added changes will open the PR