Adding Alchemist Defi Logos and Space
snapshot-labs/snapshot-spaces pull request #1184
Opened 2021-05-02 13:56 UTC by Alchemist-defi

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-05-02 14:07 UTC, Alchemist-defi commented
Added custom domain as well.

2021-05-03 02:22 UTC, gokaiorg requested changes

2021-05-03 02:22 UTC, gokaiorg commented on spaces/alchemistdefi.eth/domains.json
> +  "vote.alchemistdefi.com": "alchemistdefi.eth"
- You need to add your custom domain in this file https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json.
- Your custom domain file has to be removed.

2021-05-03 02:31 UTC, Alchemist-defi commented on spaces/alchemistdefi.eth/domains.json
> +  "vote.alchemistdefi.com": "alchemistdefi.eth"
Thanks @gokaiorg fixed that as per your suggestion

2021-05-03 02:36 UTC, gokaiorg approved these changes

2021-05-03 02:36 UTC, merged