Add Pupper logo
snapshot-labs/snapshot-spaces pull request #1189
Opened 2021-05-03 21:21 UTC by pupperdao

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-05-04 02:01 UTC, gokaiorg requested changes
- I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/pupper.eth
- The images file size should not exceed 50KB. Please reduce their weight.
- Your space name directory should be similar to your ENS. Follow this example `spaces/pupper.eth/logo.png`.

2021-05-05 00:40 UTC, pupperdao commented
Whoops! Just changed everything to reflect Pupperdao.eth and PupperDao name. Thanks!

2021-05-05 00:48 UTC, gokaiorg requested changes

2021-05-05 00:48 UTC, gokaiorg commented on skins/pupperdao.scss
> +.pupper {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.pupperdao {
```

2021-05-05 00:58 UTC, pupperdao commented
Should be fixed!

2021-05-05 01:04 UTC, gokaiorg approved these changes

2021-05-05 01:04 UTC, merged