Add logo for BLxPR
snapshot-labs/snapshot-spaces pull request #1193
Opened 2021-05-04 07:00 UTC by Primedao-admin

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-05-04 07:46 UTC, gokaiorg requested changes
Rename your images, they have a `.png.png` extension.

2021-05-04 07:46 UTC, gokaiorg commented on spaces/blxpr.eth/blxpr.eth
> +
You will need to delete this file.

2021-05-04 09:57 UTC, Primedao-admin commented on spaces/blxpr.eth/blxpr.eth
> +
Done, thanks!

2021-05-04 12:07 UTC, gokaiorg commented
Please rename your images from the example below `spaces/blxpr.eth/logo.png.png` to `spaces/blxpr.eth/logo.png`

2021-05-05 04:53 UTC, gokaiorg commented
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-05-14 07:34 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-05-14 07:34 UTC, closed without merging