Patch 11
snapshot-labs/snapshot-spaces pull request #1200
Opened 2021-05-04 14:51 UTC by GAOXING-OK

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-05-04 15:02 UTC, GAOXING-OK reviewed
ok

2021-05-04 15:02 UTC, GAOXING-OK reviewed
ok

2021-05-04 15:02 UTC, GAOXING-OK commented
ok

2021-05-05 00:36 UTC, gokaiorg requested changes

2021-05-05 00:36 UTC, gokaiorg commented on spaces/buger.eth/1
> +
Please delete this file.

2021-05-05 00:36 UTC, gokaiorg commented
Duplicate with #1181

2021-05-05 01:07 UTC, gokaiorg approved these changes

2021-05-05 01:07 UTC, merged