Update domains.json
snapshot-labs/snapshot-spaces pull request #1261
Opened 2021-05-16 10:04 UTC by Dog-Owner

Add a custom domain - gov.dogownertoken.com

- [x ] Add a custom domain for your space

2021-05-16 10:19 UTC, gokaiorg requested changes

2021-05-16 10:19 UTC, gokaiorg commented on spaces/domains.json
> +}
Please remove the extra bracket and add a comma.
```suggestion
"gov.dogownertoken.com": "dogown.eth",
```

2021-05-16 10:49 UTC, Dog-Owner reviewed
Brackets removed and comma added

2021-05-17 12:56 UTC, gokaiorg requested changes

2021-05-17 12:56 UTC, gokaiorg commented on spaces/domains.json
> -{
Please do not delete this bracket.

2021-05-18 06:03 UTC, gokaiorg approved these changes

2021-05-18 06:04 UTC, merged

2021-05-18 08:37 UTC, Dog-Owner commented
Thank you @gokaiorg