cybertime.finance
snapshot-labs/snapshot-spaces pull request #1284
Opened 2021-05-19 11:37 UTC by Whiskas1407

cybertime.finance logo and space

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-05-19 11:51 UTC, dimabosh commented
How get approve this commit?

2021-05-19 11:53 UTC, gokaiorg requested changes
Your space name directory should be similar to your ENS. Follow this example `spaces/cybertime.eth/logo.png`.

2021-05-19 11:53 UTC, gokaiorg commented on spaces/domains.json
> +  "cybertime.finance": "cybertime.finance"
You will need to use a subdomain and your ENS.
```suggestion
  "vote.cybertime.finance": "cybertime.eth"
```

2021-05-19 13:55 UTC, dimabosh commented
What we must fix now?

2021-05-19 17:47 UTC, gokaiorg requested changes
Please delete `spaces/cybertime.finance/logo.png` and `spaces/cybertime.finance/space.png` images

2021-05-29 06:26 UTC, gokaiorg commented
- Closing this PR for now, feel free to open it again once you've done the changes.
- We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.
![image](https://user-images.githubusercontent.com/8545464/120060231-c3e76200-c080-11eb-813c-32c0ab3f18c6.png)

2021-05-29 06:26 UTC, closed without merging