added honestfinance.eth space and custom domain
snapshot-labs/snapshot-spaces pull request #1297
Opened 2021-05-22 17:28 UTC by honest-finance

#### Hi! What is your PR about?

- [x] Add images for your space
- [X] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-05-22 21:22 UTC, honest-finance commented
NOTE: when I want to complete my perfil, i am receiving this error. I am signing the msg with the owner

POST /message
```
{error: "unauthorized", error_description: {}}
error: "unauthorized"
error_description: {}
```

2021-05-23 05:17 UTC, gokaiorg requested changes
- I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/honestfinance.eth
- The images file size should not exceed 50KB. Please reduce their weight.

2021-05-23 16:00 UTC, honest-finance commented
@gokaiorg thanks to help us, I just updated the comments.

All the best

2021-05-23 16:06 UTC, gokaiorg approved these changes

2021-05-23 16:06 UTC, merged