KogeCoin
snapshot-labs/snapshot-spaces pull request #1372
Opened 2021-06-11 22:11 UTC by loganbek

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-06-11 23:32 UTC, gokaiorg requested changes
We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings. Please remove them from your PR.
![image](https://user-images.githubusercontent.com/8545464/120060231-c3e76200-c080-11eb-813c-32c0ab3f18c6.png)

2021-06-11 23:32 UTC, gokaiorg commented on skins/kogecoin.scss
> +
![image](https://user-images.githubusercontent.com/8545464/121757442-bb465f80-cb47-11eb-82fc-1d7c05bada0f.png)

- The colours used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
- Please delete the extra line.

```suggestion
```

2021-06-15 00:58 UTC, loganbek commented
@gokaiorg - I removed the logos and updated the CSS. Thanks!

2021-06-15 01:19 UTC, gokaiorg requested changes

2021-06-15 01:19 UTC, gokaiorg commented on spaces/tokens.json
> +
Please do not add your token to this file, you don't need it.
```suggestion
  "0xa150db9b1fa65b44799d4dd949d922c0a33ee606": "digital-reserve-currency"
```

2021-06-15 16:05 UTC, loganbek commented on spaces/tokens.json
> +
Removed from tokens.json.

2021-06-15 16:06 UTC, loganbek commented
@gokaiorg let me know if you need anything else changed. Thanks.

2021-06-16 02:17 UTC, gokaiorg approved these changes

2021-06-16 02:18 UTC, merged