[dsbswap.eth] Add custom domain for your space
snapshot-labs/snapshot-spaces pull request #1374
Opened 2021-06-13 19:55 UTC by DSB-Team

[dsbswap.eth] Add custom domain for your space

2021-06-14 01:39 UTC, gokaiorg requested changes
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-06-15 12:58 UTC, DSB-Team commented
> There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

Yes, i just resolved.

2021-06-16 02:25 UTC, gokaiorg requested changes

2021-06-16 02:25 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.dsbswap.com":"dsbswap.eth",
Please add a space here.
```suggestion
  "vote.dsbswap.com": "dsbswap.eth",
```

2021-06-16 03:07 UTC, DSB-Team reviewed
Added a space

2021-06-16 04:00 UTC, gokaiorg approved these changes

2021-06-16 04:00 UTC, merged