Added "munchproject.io" to domains.json
snapshot-labs/snapshot-spaces pull request #1386
Opened 2021-06-17 09:26 UTC by rafzk

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [X] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-06-17 09:54 UTC, gokaiorg requested changes

2021-06-17 09:54 UTC, gokaiorg commented on spaces/aliases.json
>  }
When creating a space you do not have to edit the `aliases.json` file. Please remove it from your PR.

2021-06-18 05:52 UTC, rafzk commented on spaces/aliases.json
>  }
Reverted back the changes. Should be fine now 👍

2021-06-18 06:03 UTC, gokaiorg approved these changes

2021-06-18 06:04 UTC, merged