Create clucoin.scss, this is for `macsb.eth` or `vote.clucoin.com`
snapshot-labs/snapshot-spaces pull request #1409
Opened 2021-06-23 17:18 UTC by M4cs

#### Hi! What is your PR about?

- [X] Add or edit a skin
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-06-23 18:40 UTC, gokaiorg requested changes

2021-06-23 18:40 UTC, gokaiorg commented on skins/clucoin.scss
> +}
Please use scss indentation.
```suggestion
.clucoin {
  --primary-color: #ec008c;
  --bg-color: #0a0909;
  --text-color: #fff;
  --link-color: #ec6997;
  --heading-color: #ec008c;
  --border-color: #424242;
  --header-bg: 0a0909;
  --block-bg: #0a0909;
    
  #topnav {
    border-bottom: 4px solid #ec008c !important;
    border-image-slice: 1;
    border-image-source: linear-gradient(270deg,#ff008c,#bd0084);
  }
  
}
```

2021-06-23 22:05 UTC, M4cs commented
Fixed thank you!

2021-06-24 03:23 UTC, gokaiorg approved these changes

2021-06-24 03:23 UTC, merged