Add Custom Domain for to-the-moon.farm.eth
snapshot-labs/snapshot-spaces pull request #1423
Opened 2021-06-27 12:43 UTC by Loesil

added  "vote.to-the-moon.farm": "to-the-moon-farm.eth"

Add custom domain for your space (to-the-moon.farm.eth)

2021-06-27 18:03 UTC, gokaiorg requested changes
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-06-27 18:38 UTC, Loesil commented
OK made a new pull request

 
 

Gesendet: Sonntag, 27. Juni 2021 um 20:03 Uhr
Von: "Gokai" ***@***.***>
An: "snapshot-labs/snapshot-spaces" ***@***.***>
Cc: "Loesil" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [snapshot-labs/snapshot-spaces] Add Custom Domain for to-the-moon.farm.eth (#1423)


 

@gokaiorg requested changes on this pull request.

There is a conflict in your PR since domains.json file has been updated, can you resolve it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-27 22:13 UTC, Loesil commented
ok ignore the new pull request, merged this one. (sry first time i made a pull request)

2021-06-28 03:55 UTC, gokaiorg approved these changes

2021-06-28 03:55 UTC, merged