Plz Add apetroop Skin
snapshot-labs/snapshot-spaces pull request #1455
Opened 2021-07-08 10:07 UTC by ApeTroop

If there are any issues please advise.

#### Hi! What is your PR about?

Add ApeTroop Skin

- [ x] Add a skin

2021-07-08 12:51 UTC, gokaiorg requested changes

2021-07-08 12:51 UTC, gokaiorg commented on skins/apetroop
> +  }
Please use only theme variables. No extra custom styles are allowed except for #topnav.
```suggestion
```

2021-07-08 12:51 UTC, gokaiorg commented
Your file should have a `.scss` extension.

2021-07-09 22:05 UTC, ApeTroop commented
@gokaiorg Invalid file has been removed and correct .scss file has been added in [latest commit](https://github.com/snapshot-labs/snapshot-spaces/pull/1455/commits/2f40c6678fd764979da88b15f7ab63d275a14eac).

2021-07-10 03:45 UTC, gokaiorg approved these changes

2021-07-10 03:45 UTC, merged