add cryptoleek info
snapshot-labs/snapshot-spaces pull request #1460
Opened 2021-07-12 07:24 UTC by cryptoleek-eth

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add custom domain for your space
- [] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-07-12 07:46 UTC, gokaiorg requested changes
We have a new method to insert your images without creating a Pull Request. You can now use the Avatar field as your space settings.
![image](https://user-images.githubusercontent.com/8545464/120060231-c3e76200-c080-11eb-813c-32c0ab3f18c6.png)

2021-07-12 07:46 UTC, gokaiorg commented on spaces/tokens.json
> +  "0x67A32987a8EAA0644702C362B53B8EeBd126C20b": "leekdao.eth"
Please do not edit this file.
```suggestion
  "0xa150db9b1fa65b44799d4dd949d922c0a33ee606": "digital-reserve-currency"
```

2021-07-14 01:41 UTC, cryptoleek-eth commented
Thanks for the update. I reverted back the unnessary changes. Please have a second look.

2021-07-14 02:44 UTC, gokaiorg approved these changes

2021-07-14 02:45 UTC, merged