Create moonVault.scss
snapshot-labs/snapshot-spaces pull request #1466
Opened 2021-07-13 16:23 UTC by Loesil

Added new custom style for moonVault

#### Hi! What is your PR about?

- [ ] Add or edit a skin

2021-07-14 02:50 UTC, gokaiorg requested changes
The colours used in your skin make the submit button unreadable, please change with another.
<img width="349" alt="Capture d’écran 2021-07-14 à 09 48 27" src="https://user-images.githubusercontent.com/8545464/125553126-938eefed-0f02-42bf-ada4-5bbf647ec80e.png">

2021-07-14 02:50 UTC, gokaiorg commented on skins/moonVault.scss
> +.moonVault {
Please use only lowercase for your file name and class selector. `moonvault.scss`
```suggestion
.moonvault {
```

2021-07-14 09:52 UTC, Loesil commented
link color changed to white

2021-07-14 09:54 UTC, Loesil commented
Also changed name to lower case, like suggested

2021-07-14 15:57 UTC, gokaiorg requested changes
You still have an uppercase in the file name.

2021-07-15 13:57 UTC, Loesil commented
resolved file name issue

2021-07-15 15:43 UTC, gokaiorg approved these changes

2021-07-15 15:44 UTC, merged