add  "vote.agdeportes.com": "agdeportes.eth"
snapshot-labs/snapshot-spaces pull request #1482
Opened 2021-07-24 01:15 UTC by drpaulitoc

add new snapshots

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-07-24 03:33 UTC, gokaiorg approved these changes

2021-07-24 03:34 UTC, gokaiorg requested changes

2021-07-24 03:34 UTC, gokaiorg commented on spaces/domains.json
> +
Could you remove this empty line?
```suggestion
```

2021-07-24 17:42 UTC, drpaulitoc reviewed
I delete the last line as you recommend

2021-07-25 01:24 UTC, drpaulitoc reviewed
I deleted the last line as you request

2021-07-25 02:47 UTC, gokaiorg approved these changes

2021-07-25 02:47 UTC, merged