Create agdeportes.scss
snapshot-labs/snapshot-spaces pull request #1484
Opened 2021-07-24 23:20 UTC by drpaulitoc

createskin

#### Hi! What is your PR about?

- [x ] Add or edit a skin
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-07-25 02:52 UTC, gokaiorg requested changes
The colours used in your skin make the interface unreadable, please change with others.
<img width="735" alt="Capture d’écran 2021-07-25 à 09 50 37" src="https://user-images.githubusercontent.com/8545464/126886084-02dc4628-d041-45cd-82eb-c9bb40f4a492.png">

2021-07-25 02:52 UTC, gokaiorg commented on skins/agdeportes.scss
> +  --primary-color: #fde25;
Please correct your hexademical colour.
```suggestion
  --primary-color: #fde250;
```

2021-07-26 15:30 UTC, drpaulitoc reviewed
I changed the color as you recomend

2021-07-27 04:31 UTC, gokaiorg approved these changes

2021-07-27 04:32 UTC, merged