add nftorbit.io
snapshot-labs/snapshot-spaces pull request #1489
Opened 2021-07-26 10:59 UTC by nftorbit

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-07-26 13:06 UTC, gokaiorg requested changes

2021-07-26 13:06 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.nftorbit.io": "nftorbit.eth"
A comma is missing at the end of the line above your sub-domain.
```suggestion
  "vote.dopeshibas.fun": "dopeshibas.eth",
  "vote.nftorbit.io": "nftorbit.eth"
```
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?

2021-07-28 09:41 UTC, nftorbit commented
Yes Resolved.


On Mon, 26 Jul 2021 at 18:36, Gokai ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In spaces/domains.json
> <https://github.com/snapshot-labs/snapshot-spaces/pull/1489#discussion_r676584799>
> :
>
> >    "vote.dopeshibas.fun": "dopeshibas.eth"
>
> +  "vote.nftorbit.io": "nftorbit.eth"
>
>
> A comma is missing at the end of the line above your sub-domain.
> ⬇️ Suggested change
>
> -  "vote.dopeshibas.fun": "dopeshibas.eth"
>
> -  "vote.nftorbit.io": "nftorbit.eth"
>
> +  "vote.dopeshibas.fun": "dopeshibas.eth",
>
> +  "vote.nftorbit.io": "nftorbit.eth"
>
>
> There is a conflict in your PR since domains.json file has been updated,
> can you resolve it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/snapshot-labs/snapshot-spaces/pull/1489#pullrequestreview-714818709>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU2ARRY5QWYHGY2WXBN35F3TZVMUZANCNFSM5A73JVHA>
> .
>

2021-07-28 12:14 UTC, gokaiorg commented
@nftorbit 
To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

2021-07-28 12:16 UTC, gokaiorg commented
Duplicate with #1494

2021-07-28 12:16 UTC, closed without merging