Add Moonsama skin
snapshot-labs/snapshot-spaces pull request #1584
Opened 2021-09-29 08:26 UTC by mevanabey

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-09-29 11:30 UTC, gokaiorg requested changes

2021-09-29 11:30 UTC, gokaiorg commented on skins/expectchaos.scss
> +  }
Please use only theme variables. No extra custom styles are allowed.
```suggestion
```

2021-09-29 19:51 UTC, mevanabey commented on skins/expectchaos.scss
> +  }
Updated.

2021-09-30 02:25 UTC, gokaiorg approved these changes

2021-09-30 02:25 UTC, merged