Creating Element Finance skin file
snapshot-labs/snapshot-spaces pull request #1594
Opened 2021-10-01 17:43 UTC by tinahaibodi

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- ~Add images for your space~ (deprecated) Add the image URL on the space settings directly
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-10-02 01:34 UTC, gokaiorg requested changes

2021-10-02 01:34 UTC, gokaiorg commented on skins/element-finance.scss
> +  }
Please keep extra styles only for #topnav.
```suggestion
  #topnav {
    background-color: #005EBE;
    border-bottom: 4px solid #005EBE !important;
    border-image-slice: 1;
    border-image-source: linear-gradient(to left, #005EBE, #78D3E2);
  }
```

2021-10-04 16:37 UTC, tinahaibodi commented
Making changes

2021-10-05 03:28 UTC, gokaiorg requested changes

2021-10-05 03:28 UTC, gokaiorg commented on skins/element-finance.scss
> +}
The colours used in your skin make the submit button unreadable, please change with others.
<img width="362" alt="Capture d’écran 2021-10-05 à 10 26 44" src="https://user-images.githubusercontent.com/8545464/135955372-0df84e3b-9c71-48ce-9499-dfc321bcd671.png">

2021-11-13 09:15 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-11-13 09:15 UTC, closed without merging