Update domains.json
snapshot-labs/snapshot-spaces pull request #1650
Opened 2021-11-03 11:02 UTC by joshuaarmah

#### Hi! What is your PR about?

Added a domain solarmoon.eth/vote.solarmoon.app

2021-11-04 06:51 UTC, gokaiorg requested changes
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy.

2021-11-06 00:58 UTC, joshuaarmah commented
This is te snapshot URL
https://snapshot.org/#/vote.solarmoon.eth

Our space is under vote.solarmoon.app dns wise it is configured on our end

2021-11-06 09:36 UTC, gokaiorg requested changes

2021-11-06 09:36 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.solarmoon.app": "solarmoon.eth",
Use your ENS here.
```suggestion
  "vote.solarmoon.app": "vote.solarmoon.eth",
```

2021-12-01 05:29 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-12-01 05:29 UTC, closed without merging