Create 6ix.scss
snapshot-labs/snapshot-spaces pull request #1667
Opened 2021-11-11 14:20 UTC by danielbarankin

#### Hi! What is your PR about?

**- [ ] Add or edit a skin**
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2021-11-13 09:09 UTC, gokaiorg requested changes
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
<img width="493" alt="Capture d’écran 2021-11-13 à 16 07 30" src="https://user-images.githubusercontent.com/8545464/141613046-97456e08-3b24-4ae2-9833-33989fbe97e2.png">

2021-11-13 09:09 UTC, gokaiorg commented on skins/6ix.scss
> +}
Please use only theme variables. No extra custom styles are allowed except for #topnav.
```suggestion
    #topnav {
        font-size: 0;
        line-height: 0;
        width: 0;
        height: 0;
        display: none;
    }
}
```

2021-11-22 17:26 UTC, danielbarankin commented
Please review, thank you :)

2021-11-25 02:43 UTC, gokaiorg requested changes

2021-11-25 02:43 UTC, gokaiorg commented on skins/six.scss
> +    }
Please use only colour styles, don't hide the top nav.
```suggestion
```

2021-12-26 05:33 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-12-26 05:33 UTC, closed without merging

2021-12-26 13:27 UTC, danielbarankin commented
Hi @gokaiorg , this PR is correctly configured. Fabien approved it. Please re-open and approve.

2021-12-26 21:06 UTC, bonustrack commented
@danielbarankin Please make a single PR with all the required changes, this PR missing adding style in the index.js file. Also the changes on #topnav wont work well, did you tested it? This would hide the topnav, so there wont be way to connect wallet.

2021-12-26 21:10 UTC, danielbarankin commented
Thank you cc’ing Adnan

  
On Sun, Dec 26 2021 at 4:06 PM, Fabien < ***@***.*** > wrote:

> 
> 
> 
> 
> 
> 
> 
> @danielbarankin ( https://github.com/danielbarankin ) Please make a single
> PR with all the required changes, this PR missing adding style in the
> index.js file. Also the changes on #topnav wont work well, did you tested
> it? This would hide the topnav, so there wont be way to connect wallet.
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub (
> https://github.com/snapshot-labs/snapshot-spaces/pull/1667#issuecomment-1001242033
> ) , or unsubscribe (
> https://github.com/notifications/unsubscribe-auth/AH4DTB5ZFTFWCM6TCCZR6XLUS57WZANCNFSM5H2SNMFQ
> ).
> You are receiving this because you were mentioned. Message ID: <snapshot-labs/snapshot-spaces/pull/1667/c1001242033
> @ github. com>
> 
> 
>