Adding ParaSwap to domains & aliases
snapshot-labs/snapshot-spaces pull request #1744
Opened 2021-12-14 20:03 UTC by mounibec

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [x] Add an alias to migrate your space

2021-12-15 03:28 UTC, gokaiorg requested changes

2021-12-15 03:28 UTC, gokaiorg commented on spaces/aliases.json
> +  "paraswap": "paraswap-dao.eth",
The aliases file is used for space migrations, so you should not need to edit it.
```suggestion
```

2021-12-26 05:36 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-12-26 05:36 UTC, closed without merging

2021-12-26 08:23 UTC, mounibec commented
> Closing this PR for now, feel free to open it again once you've done the changes.

Created a new PR https://github.com/snapshot-labs/snapshot-spaces/pull/1764