add vote.alphadao.money
snapshot-labs/snapshot-spaces pull request #1761
Opened 2021-12-25 04:03 UTC by 0xmatt1

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2021-12-26 05:31 UTC, gokaiorg requested changes

2021-12-26 05:31 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.alphadao.money": "alphagov.eth"
A comma is missing at the end of the line above your sub-domain.
```suggestion
  "signal.paladin.vote": "palvote.eth",
  "vote.alphadao.money": "alphagov.eth"
```

2021-12-27 14:01 UTC, 0xmatt1 commented
Updated requested changes

2021-12-29 04:05 UTC, gokaiorg commented
There is a conflict in your PR since the `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

2021-12-29 17:36 UTC, 0xmatt1 commented
updated, moved our entry a few lines up

2021-12-30 02:53 UTC, gokaiorg approved these changes

2021-12-30 02:53 UTC, merged