Update domains.json
snapshot-labs/snapshot-spaces pull request #1795
Opened 2022-01-06 08:07 UTC by lolieatapple

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [X] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-01-07 06:43 UTC, lolieatapple commented
add custom vote domain for huckleberry.

2022-01-09 00:20 UTC, gokaiorg requested changes

2022-01-09 00:20 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.huckleberry.finance":"huckleberrydex.eth"
Please add a space between sub-domain and ENS.
```suggestion
  "vote.huckleberry.finance": "huckleberrydex.eth"
```

2022-01-09 01:05 UTC, gokaiorg commented
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

2022-01-10 03:46 UTC, lolieatapple commented
ok, I have changed it, please help to review again.

2022-01-10 03:51 UTC, gokaiorg requested changes

2022-01-10 03:51 UTC, gokaiorg commented on spaces/domains.json
> +  "gov.tethys.finance": "tethysswap.eth",
Please delete the duplicated row.
```suggestion
```

2022-01-10 06:57 UTC, lolieatapple commented on spaces/domains.json
> +  "vote.huckleberry.finance":"huckleberrydex.eth"
Ok

2022-01-14 04:14 UTC, gokaiorg approved these changes

2022-01-14 04:14 UTC, merged