update: add skin styles
snapshot-labs/snapshot-spaces pull request #1816
Opened 2022-01-14 03:51 UTC by HeyMichelle

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-01-14 04:23 UTC, gokaiorg requested changes

2022-01-14 04:23 UTC, gokaiorg commented on skins/totemearth.scss
> +.thirm {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.totemearth {
```

2022-01-14 09:26 UTC, HeyMichelle reviewed
I see I didn't catch that initially, thank you for correcting. Looks as expected.

2022-01-17 04:10 UTC, gokaiorg approved these changes

2022-01-17 04:11 UTC, merged