add vote.solace.fi
snapshot-labs/snapshot-spaces pull request #1821
Opened 2022-01-16 16:28 UTC by leonardishere

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-01-17 04:24 UTC, gokaiorg requested changes

2022-01-17 04:24 UTC, gokaiorg commented on skins/solace.scss
> +  }
This will make images transparent. You should delete this file from your PR.
```suggestion
  img {
    --tw-bg-opacity: 0;
  }
```

2022-01-17 16:26 UTC, leonardishere commented on skins/solace.scss
> +  }
I would like the background of the avatar to be transparent. Is there a better way to handle it? I don't see a unique class on the img.
This is how the transparent avatar looks with a white background
![Screenshot from 2022-01-16 11-12-58](https://user-images.githubusercontent.com/14011462/149805782-02b1f070-4b4b-426d-9bfd-8bbfb4b9bc35.png)
![Screenshot from 2022-01-16 11-13-10](https://user-images.githubusercontent.com/14011462/149805785-cb2f8b73-4128-46e3-8bb3-60255d7178c5.png)
I filled in the avatar with a black background but that didn't help
![Screenshot from 2022-01-16 11-07-51](https://user-images.githubusercontent.com/14011462/149805892-c8578ba9-7e2d-471a-9239-f4bd40bbe425.png)
![Screenshot from 2022-01-16 11-08-11](https://user-images.githubusercontent.com/14011462/149805896-d52a4dfa-9e1a-478c-a938-ae0d7246f696.png)
This is how it looks with --tw-bg-opacity=0
![Screenshot from 2022-01-17 08-24-46](https://user-images.githubusercontent.com/14011462/149806195-7d107ff0-7041-41f5-8894-93d18f248b5f.png)
![Screenshot from 2022-01-17 08-24-57](https://user-images.githubusercontent.com/14011462/149806197-93544c73-71c7-47b5-99ed-65918a3f276f.png)

2022-02-02 00:51 UTC, leonardishere commented on skins/solace.scss
> +  }
> It could work with a png image where the centre of the circle is transparent?

That's what's there now
https://snapshot.org/#/solacefi.eth
![Screenshot from 2022-02-01 16-43-52](https://user-images.githubusercontent.com/14011462/152075782-7575cb3c-e351-4db4-a4e7-58918420edad.png)
![Screenshot from 2022-02-01 16-44-36](https://user-images.githubusercontent.com/14011462/152075790-e17babcb-7f13-4f72-981b-1c59ebad0903.png)

2022-02-04 04:34 UTC, gokaiorg commented on skins/solace.scss
> +  }
@bonustrack Do you have a recommendation for this?

2022-02-07 05:46 UTC, gokaiorg commented on skins/solace.scss
> +  }
@samuveth Do you have an opinion about using this method for the image background?

2022-03-28 20:43 UTC, leonardishere commented on skins/solace.scss
> +  }
@gokaiorg I removed the scss, can you please re review?

2022-03-29 02:54 UTC, gokaiorg requested changes

2022-03-29 02:54 UTC, gokaiorg commented on skins/solace.scss
> +.solace { }
@leonardishere You should rather delete the empty css file so that we can merge your subdomain!

2022-03-29 04:01 UTC, leonardishere commented on skins/solace.scss
> +.solace { }
@gokaiorg deleted

2022-03-30 02:21 UTC, gokaiorg approved these changes

2022-03-30 02:21 UTC, merged