Added theartistdao.com address
snapshot-labs/snapshot-spaces pull request #1833
Opened 2022-01-21 08:19 UTC by nickjuntilla

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ X] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-01-22 06:41 UTC, gokaiorg requested changes

2022-01-22 06:41 UTC, gokaiorg commented on spaces/domains.json
> +  "theartistdao.com": "theartistdao.eth",
You should use a subdomain.
```suggestion
  "vote.theartistdao.com": "theartistdao.eth",
```

2022-01-23 04:44 UTC, nickjuntilla commented on spaces/domains.json
> +  "theartistdao.com": "theartistdao.eth",
Is this a requirement? We are not using this domain for anything other than this purpose at this time.

2022-01-25 07:39 UTC, bonustrack commented on spaces/domains.json
> +  "theartistdao.com": "theartistdao.eth",
This is not a requirement, it would work well with the root domain theartistdao.com

2022-01-25 07:40 UTC, merged