Create prepo.scss
snapshot-labs/snapshot-spaces pull request #1835
Opened 2022-01-23 00:06 UTC by liqwiz

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-01-25 02:26 UTC, gokaiorg requested changes
You will also need to list your skin on this file:
https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

2022-01-25 02:26 UTC, gokaiorg commented on skins/prepo.scss
> +  }
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
```suggestion
```

2022-01-25 02:26 UTC, gokaiorg commented on skins/prepo.scss
> +  }
<img width="1077" alt="Capture d’écran 2022-01-25 à 09 23 00" src="https://user-images.githubusercontent.com/8545464/150899055-234d8271-96ae-49ee-a204-b40be49df988.png">

2022-01-28 03:02 UTC, liqwiz commented
Thanks for the review @gokaiorg, I've fixed the theme and updated the index file.

2022-01-29 05:19 UTC, gokaiorg requested changes

2022-01-29 05:19 UTC, gokaiorg commented on skins/prepo.scss
> +    background-color: #454699;
Please add the background colour globally, you can edit the #topnav border only. 
```suggestion
```

2022-01-29 05:19 UTC, gokaiorg commented on skins/prepo.scss
> +  }
```suggestion
```

2022-02-02 03:26 UTC, liqwiz commented
> Please add the background colour globally, you can edit the #topnav border only.

Hi @gokaiorg, thanks for your response. 

We copied the Yearn Skin almost exactly (https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/yearn.scss), only changing the primary brand color. Is no longer a valid approach?

2022-02-04 04:36 UTC, gokaiorg commented
@bonustrack Can the types of Yearn styles be reproduced?

2022-02-14 00:30 UTC, liqwiz commented
Hi @gokaiorg, just following up here. 

Is it not OK to modify the header like Yearn or do you have some other suggestions how I can achieve this effect?

Thanks.

2022-02-17 04:27 UTC, gokaiorg approved these changes

2022-02-17 04:28 UTC, merged