create cryptopugz.scss
snapshot-labs/snapshot-spaces pull request #1850
Opened 2022-01-28 02:39 UTC by Blockchaindevelopment01

just added Cryptopugz.scss to snapshot skins

#### Hi! What is your PR about?

- [yes] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-01-28 03:10 UTC, Blockchaindevelopment01 commented
if your could help me with this ill greatly appreciate it.

2022-01-29 05:19 UTC, gokaiorg requested changes
To create your skin will also need to list your skin on this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

2022-01-29 06:45 UTC, Blockchaindevelopment01 commented
I think i just did a pull request for the second skin file:  https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js let me know if theirs anything else I need to do, ill greatly appreciate it.

2022-01-30 03:20 UTC, gokaiorg approved these changes

2022-02-01 05:25 UTC, merged