add darkmatter
snapshot-labs/snapshot-spaces pull request #1859
Opened 2022-01-31 01:46 UTC by aobr95

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-02-01 07:05 UTC, gokaiorg requested changes
There is a conflict in your PR, can you resolve it?

2022-02-01 07:05 UTC, gokaiorg commented on spaces/domains.json
> +  "gov.alluo.io": "alluo.eth"
You will miss a comma at the end of he 
```suggestion
  "gov.alluo.io": "alluo.eth",
```

2022-02-01 11:34 UTC, aobr95 commented on spaces/domains.json
> +  "gov.alluo.io": "alluo.eth"
oh i didn't see that updated

2022-02-07 05:47 UTC, gokaiorg approved these changes

2022-02-07 05:47 UTC, merged