create deluxe.scss
snapshot-labs/snapshot-spaces pull request #1863
Opened 2022-02-03 10:44 UTC by pixel-mage

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-02-04 04:44 UTC, gokaiorg requested changes

2022-02-04 04:44 UTC, gokaiorg commented on skins/deluxe.scss
> +}
The colors used in your skin make the interface unreadable in light mode, please change with others or remove the skin to use the default theme.
<img width="1029" alt="Capture d’écran 2022-02-04 à 11 43 08" src="https://user-images.githubusercontent.com/8545464/152473115-bdba3c18-3694-46f9-a237-0a7eb4fdfce8.png">

2022-02-04 04:44 UTC, gokaiorg commented
To create your skin will also need to list your skin on this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

2022-02-11 03:18 UTC, pixel-mage commented
yes we will just use the default theme thanks

2022-02-11 03:18 UTC, closed without merging