forward domain added & skin added
snapshot-labs/snapshot-spaces pull request #1928
Opened 2022-03-02 05:19 UTC by dhavalalite

#### Hi! What is your PR about?

- [ ] Add or edit a skin

- [] Add a custom domain for your space

- [ ] Add an alias to migrate your space

2022-03-02 05:29 UTC, Yara1990 approved these changes
Looks good, merging now

2022-03-02 05:31 UTC, Yara1990 reviewed
Good to go live

2022-03-07 07:53 UTC, Yara1990 commented
@gokaiorg Kindly review the above fixes.

2022-03-07 07:53 UTC, Yara1990 commented
> 

@gokaiorg Kindly review the above fixes.

2022-03-07 15:28 UTC, gokaiorg commented
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

2022-03-08 13:34 UTC, Yara1990 commented
@gokaiorg We have resolved it. Please approve the same.

2022-03-09 07:00 UTC, gokaiorg requested changes

2022-03-09 07:00 UTC, gokaiorg commented on skins/forward.scss
> +.forwardprotocol {
Your class name should be similar to file name.
```suggestion
.forward {
```

2022-03-14 02:19 UTC, gokaiorg approved these changes

2022-03-14 02:19 UTC, merged