Add Hifi domain
snapshot-labs/snapshot-spaces pull request #1955
Opened 2022-03-16 15:55 UTC by scorpion9979

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

Note: We are Hifi Finance and we would like to use our token (MFT) for voting on our space.

2022-03-17 03:29 UTC, gokaiorg requested changes

2022-03-17 03:29 UTC, gokaiorg commented on spaces/tokens.json
> +  "0xDF2C7238198Ad8B389666574f2d8bc411A4b7428": "mft",
You will not need to add your token to this file.
```suggestion
```

2022-03-17 18:08 UTC, scorpion9979 reviewed
I've reverted the change to "spaces/tokens.json".

2022-03-20 04:50 UTC, gokaiorg approved these changes

2022-03-20 04:50 UTC, merged