saynotorugs.eth
snapshot-labs/snapshot-spaces pull request #1957
Opened 2022-03-18 06:54 UTC by DreesusChrist

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-03-20 04:51 UTC, gokaiorg requested changes

2022-03-20 04:51 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.rug.farm": "saynotorugs.eth"
A comma is missing at the end of the line above your sub-domain.
```suggestion
  "vote.komorebinosekai.com": "komorebi-no-sekai.eth",
  "vote.rug.farm": "saynotorugs.eth"
```

2022-03-22 19:51 UTC, DreesusChrist reviewed
Ah thank you for finding this! Do I need to resubmit the request with changes?

2022-03-24 03:48 UTC, gokaiorg approved these changes

2022-03-24 03:48 UTC, merged