Update domains.json
snapshot-labs/snapshot-spaces pull request #1970
Opened 2022-03-24 18:23 UTC by athamefinance

athame finance

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [X] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-03-25 00:33 UTC, gokaiorg requested changes
There is a conflict in your PR since `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list
].

2022-03-25 00:57 UTC, athamefinance commented
I did actually add in between :}

2022-03-25 02:04 UTC, gokaiorg requested changes

2022-03-25 02:04 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.athame.finance":  "athamefinance.eth",
Please could you remove the extra space between key and value?
```suggestion
  "vote.athame.finance": "athamefinance.eth",
```

2022-03-26 07:06 UTC, gokaiorg commented
To update your fork with the remote version of snapshot-spaces you can try these GIT commands then commit your changes again.
`git remote add upstream https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

2022-03-26 11:50 UTC, closed without merging