Update domains.json
snapshot-labs/snapshot-spaces pull request #1999
Opened 2022-04-05 23:50 UTC by FMercedes

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-04-07 04:08 UTC, gokaiorg requested changes

2022-04-07 04:08 UTC, gokaiorg commented on spaces/domains.json
> +  "governance.cyberestate.io: "cyberrealestate.eth",
You are missing a quote.
```suggestion
  "governance.cyberestate.io": "cyberrealestate.eth",
```

2022-06-21 23:13 UTC, Gemk83 approved these changes

2022-06-23 03:23 UTC, gokaiorg commented
There is a conflict in your PR since the `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

2022-06-23 03:25 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2022-06-23 03:25 UTC, closed without merging