added metfi dao skin
snapshot-labs/snapshot-spaces pull request #2095
Opened 2022-06-08 17:00 UTC by metfi

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-06-09 02:48 UTC, gokaiorg requested changes

2022-06-09 02:48 UTC, gokaiorg commented on skins/metfi-dao.scss
> +.mantra-dao {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.metfi-dao {
```

2022-06-09 04:20 UTC, gokaiorg approved these changes

2022-06-09 04:20 UTC, merged

2024-03-10 16:27 UTC, misterkim4422 commented
Very good