Create gogoprotocol.scss
snapshot-labs/snapshot-spaces pull request #2128
Opened 2022-06-25 12:25 UTC by daedlock

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-06-27 04:47 UTC, gokaiorg requested changes

2022-06-27 04:47 UTC, gokaiorg commented on skins/gogoprotocol.scss
> +  color-scheme: dark;
You won't need to add color scheme here. Please use the same format as https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/complifi.scss
```suggestion
```

2022-06-27 14:50 UTC, daedlock commented
@gokaiorg fixed. thanks

2022-06-28 03:35 UTC, gokaiorg approved these changes

2022-06-28 03:36 UTC, merged