Add moonwell skin
snapshot-labs/snapshot-spaces pull request #2191
Opened 2022-08-19 02:07 UTC by moonwell-octavius

#### Hi! What is your PR about?

- [X] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

This PR adds in the `moonwell` skin 🚀

2022-08-19 07:33 UTC, gokaiorg requested changes
Your style file is too large. Some classes like `bg-skin-header-bg` seem to not exist. Can you make it a little lighter?

2022-08-19 16:31 UTC, moonwell-octavius commented
Hi @gokaiorg, apologies, I used https://github.com/snapshot-labs/snapshot-spaces/blob/7c9d557d9ccce05771ce6017da7d099a6a5b510d/skins/mero.scss#L17-L30 as a template, and it looks like those classes are no longer used, so I'll happily remove them (meant to last night but forgot!). 

Beyond that though I spent a decent amount of time getting this put together so our space looks good (and fixes some issues we got reports of like the yay/nay buttons not being clear about what's selected). 

Can I just pull out the `bg-skin-header-bg` rules and leave it as is please? If not, when you say "too large" can you be more specific around what would be acceptable?

2022-08-19 16:32 UTC, moonwell-octavius commented
Should be fixed @gokaiorg! Thanks for taking a look so fast :)

2022-08-20 10:41 UTC, gokaiorg approved these changes

2022-08-20 10:42 UTC, merged