Add Planet memes domain and skin
snapshot-labs/snapshot-spaces pull request #2246
Opened 2022-09-16 00:23 UTC by headria

2022-09-16 03:01 UTC, gokaiorg requested changes

2022-09-16 08:32 UTC, headria commented on spaces/aliases.json
> +  "sushi": "sushigov.eth",
solved

2022-09-17 04:09 UTC, gokaiorg requested changes
To create your skin will also need to list your skin on this file: https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/index.js

2022-09-19 03:17 UTC, gokaiorg requested changes

2022-09-19 03:17 UTC, gokaiorg commented on skins/planetmemes.scss
> +.trustwallet {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.planetmemes {
```

2022-09-19 10:34 UTC, merged