Adding dynodao.eth
snapshot-labs/snapshot-spaces pull request #2283
Opened 2022-10-11 02:50 UTC by blockchainreg

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-10-12 03:27 UTC, gokaiorg requested changes

2022-10-12 03:27 UTC, gokaiorg commented on spaces/domains.json
>    "vote.cirip.io": "cirip.io"
A comma is missing at the end of the line of your sub-domain.
```suggestion
  "vote.cirip.io": "cirip.io",
```

2022-10-21 03:48 UTC, gokaiorg requested changes
There is a conflict in your PR since the `domains.json` file has been updated, can you resolve it?
To prevent conflicts, it is recommended to add your subdomain between two existing domains rather than at the end or beginning of the list.

2022-10-25 10:16 UTC, blockchainreg commented
hows everything looking

2022-10-26 05:05 UTC, gokaiorg commented
> hows everything looking

Hey @blockchainreg The conflict still has to be resolved.

2022-10-26 07:37 UTC, closed without merging