✨ add lakan-intractive skin
snapshot-labs/snapshot-spaces pull request #2285
Opened 2022-10-12 06:19 UTC by johnpaulcas

#### Hi! What is your PR about?

- [X] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2022-10-13 03:19 UTC, gokaiorg requested changes

2022-10-13 03:19 UTC, gokaiorg commented on skins/index.js
> +  lakanInteractive,
Please use the following format:
```suggestion
  "lakan-interactive": lakanInteractive,
```

2022-10-13 08:43 UTC, johnpaulcas commented on skins/index.js
> +  lakanInteractive,
Hi @gokaiorg, changed to format above `"lakan-interactive": lakanInteractive,`, thanks!

2022-10-14 02:17 UTC, gokaiorg approved these changes

2022-10-14 02:21 UTC, merged