Added vote.primapes.gg
snapshot-labs/snapshot-spaces pull request #2351
Opened 2022-12-09 22:35 UTC by sfichera

Added a custom domain for your space

2022-12-12 03:12 UTC, gokaiorg requested changes

2022-12-12 03:12 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.primapes.gg":"primapes.eth"
Please add a space between sub domain and ENS.
```suggestion
  "vote.primapes.gg": "primapes.eth"
```

2022-12-13 04:49 UTC, gokaiorg approved these changes

2022-12-13 04:50 UTC, merged

2022-12-13 15:57 UTC, sfichera commented
Hey @gokaiorg how are you? I'm having an error while calling the api:
https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=vote.primapes.gg

Response:
_{"message": "Internal server error"}_

If i call it without the subdomain like this:
https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=primapes.gg

I'm getting the following lines:

_Adding domain "primapes.gg". 
Creating new domain failed - domain might already exist. 
Requesting new SSL failed - domain might not be pointed correctly. 
SSL redirect forced._

And i'm not able to browse vote.primapes.gg with https...

Could you please help me out? Thanks!!