Update domains.json
snapshot-labs/snapshot-spaces pull request #2385
Opened 2023-01-19 13:36 UTC by xEuathlus

Add Hodl.finance domain

2023-01-20 03:21 UTC, gokaiorg requested changes
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/hodl.finance

2023-01-24 12:24 UTC, xEuathlus commented
resolved it is hft.eth

2023-01-30 03:33 UTC, gokaiorg requested changes

2023-01-30 03:33 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.hodl.finance": "hodl.finance",
You will need to edit your ENS here
```suggestion
  "vote.hodl.finance": "hft.eth",
```

2023-02-27 03:39 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2023-02-27 03:39 UTC, closed without merging