added new custom domain
snapshot-labs/snapshot-spaces pull request #2415
Opened 2023-03-07 13:42 UTC by sachin-sanjay

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [X] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-03-09 03:02 UTC, gokaiorg requested changes

2023-03-09 03:02 UTC, gokaiorg commented on spaces/domains.json
> +  "proposals.unore.io":"unoredao.eth",
You will need to add a space between your domain and your DNS value.
```suggestion
  "proposals.unore.io": "unoredao.eth",
```

2023-03-09 06:07 UTC, sachin-sanjay commented
Hi, sorry about that I've fixed it now.

2023-03-13 07:38 UTC, gokaiorg approved these changes

2023-03-13 07:38 UTC, merged