🎨 add breederdao skin
snapshot-labs/snapshot-spaces pull request #2444
Opened 2023-04-17 08:58 UTC by johnpaulcas

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-04-19 03:07 UTC, gokaiorg requested changes
To create your skin will also need to add your space name on index table: https://github.com/snapshot-labs/snapshot-spaces/blob/cf364b909692be68668a87701943bd65f217a6b0/skins/index.js#L302

2023-04-19 03:22 UTC, johnpaulcas commented
> To create your skin will also need to add your space name on index table:
> 
> https://github.com/snapshot-labs/snapshot-spaces/blob/cf364b909692be68668a87701943bd65f217a6b0/skins/index.js#L302

hi @gokaiorg I guess its already added 👉 https://github.com/snapshot-labs/snapshot-spaces/pull/2444/files#diff-399e25f732c47d0534d12a9ab3cd620da0e32fcf3c9ef7f865e5b4c96f0e5dfb

2023-04-19 03:26 UTC, johnpaulcas commented
> To create your skin will also need to add your space name on index table:
> 
> https://github.com/snapshot-labs/snapshot-spaces/blob/cf364b909692be68668a87701943bd65f217a6b0/skins/index.js#L302

hi @gokaiorg resolved this issue 👉 https://github.com/snapshot-labs/snapshot-spaces/pull/2444/files#diff-399e25f732c47d0534d12a9ab3cd620da0e32fcf3c9ef7f865e5b4c96f0e5dfbR340

thanks!

2023-04-21 06:50 UTC, gokaiorg requested changes

2023-04-21 06:50 UTC, gokaiorg commented on skins/index.js
> +  breederdaoSpace,
When you use a dash, you must use this naming convention.
```suggestion
  "breederdao-space": breederdaoSpace,
```

2023-04-21 20:24 UTC, johnpaulcas commented on skins/index.js
> +  breederdaoSpace,
> When you use a dash, you must use this naming convention.

resolved this issue @gokaiorg thanks!

2023-04-23 20:39 UTC, sany12345 reviewed
Good

2023-04-24 02:26 UTC, gokaiorg approved these changes

2023-04-24 02:26 UTC, merged