patch: Added `dao.pearl.club` to `domains.json`
snapshot-labs/snapshot-spaces pull request #2450
Opened 2023-04-28 22:27 UTC by 0xRektora

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-04-29 07:33 UTC, gokaiorg requested changes
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/pearlclubdao.eth

2023-04-29 19:27 UTC, BertsLifee approved these changes

2023-05-01 18:04 UTC, 0xRektora commented
ENS confusion, should be good now!

2023-05-01 20:06 UTC, 0xRektora commented
Closing to reopen a new one.

2023-05-01 20:06 UTC, closed without merging