Molens custom domain
snapshot-labs/snapshot-spaces pull request #2456
Opened 2023-05-03 15:00 UTC by DanIsNearby

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [X] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-05-04 05:48 UTC, gokaiorg requested changes

2023-05-04 05:48 UTC, gokaiorg commented on spaces/domains.json
> +
A comma is missing at the end of the line above your sub-domain. Please remove also the empty line.
```suggestion
  "dao.pearl.club": "pearlclubdao.eth",
  "vote.molens.xyz": "molens.eth"
```

2023-05-04 09:11 UTC, DanIsNearby commented
@gokaiorg thx commited the changes

2023-05-05 04:25 UTC, gokaiorg approved these changes

2023-05-05 04:25 UTC, merged