Added ButaneDAO
snapshot-labs/snapshot-spaces pull request #2471
Opened 2023-05-20 23:36 UTC by bbcchain

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-05-21 07:21 UTC, gokaiorg requested changes

2023-05-21 07:21 UTC, gokaiorg commented on spaces/aliases.json
> +  "butanedao.eth": "butanedao.eth",
Use aliases.json when you aim to proceed to a space migration.
```suggestion
```

2023-05-22 06:11 UTC, bbcchain commented on spaces/aliases.json
> +  "butanedao.eth": "butanedao.eth",
> Use aliases.json when you aim to proceed to a space migration.

I have updated the PR

2023-05-24 02:54 UTC, gokaiorg requested changes

2023-05-24 02:54 UTC, gokaiorg commented on spaces/aliases.json
> +  "vote.butanedao.io": "butanedao.eth",
You don't need to edit the aliases file, it is reserved for space migrations. 
```suggestion
```

2023-05-27 14:23 UTC, bbcchain reviewed
I hope this is correct

2023-05-28 01:25 UTC, gokaiorg commented
> I hope this is correct

Nope 😁 By editing the aliases file you mean you want to migrate https://snapshot.org/#/butanedao.io to https://snapshot.org/#/butanedao.eth. But the butenedao.io space does not exist.

2023-06-09 08:06 UTC, bbcchain commented
I deleted the space thinking I could redo it. Im trying to get vote.butanedao.io to work. We have also added our chain in chain list. Could you please make necessary changes?

Thank you

2023-06-12 01:46 UTC, gokaiorg commented
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/butanedao.eth

2023-08-27 03:56 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2023-08-27 03:56 UTC, closed without merging