Update domains.json
snapshot-labs/snapshot-spaces pull request #2476
Opened 2023-05-29 10:28 UTC by ampleswap

Please add this domain i have updated cname on server 
i have submit 2 time but not showing on dashboard 
https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json
AmpleSwap
The Best AMM Dex on BNB Smart Chain and Polygon providing friendly trading and better project support

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [ ] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-05-30 05:14 UTC, gokaiorg approved these changes

2023-05-30 05:15 UTC, gokaiorg requested changes

2023-05-30 05:15 UTC, gokaiorg commented on spaces/domains.json
> +   "dao.ampleswap.com": "ampleswap.eth",
Please remove extra space before your line.
```suggestion
  "dao.ampleswap.com": "ampleswap.eth",
```

2023-05-31 03:03 UTC, gokaiorg approved these changes

2023-05-31 03:03 UTC, merged

2023-05-31 05:25 UTC, ampleswap commented
What is the next step for us
Do we will get some files to upload on subdomain

Kind Regards,

Amrendra

From: Gokai Labs ***@***.***>
Sent: Wednesday, May 31, 2023 8:34 AM
To: snapshot-labs/snapshot-spaces ***@***.***>
Cc: Ampleswap Info ***@***.***>; Author ***@***.***>
Subject: Re: [snapshot-labs/snapshot-spaces] Update domains.json (PR #2476)


Merged #2476<https://github.com/snapshot-labs/snapshot-spaces/pull/2476> into master.

—
Reply to this email directly, view it on GitHub<https://github.com/snapshot-labs/snapshot-spaces/pull/2476#event-9384853434>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVCTFFDVK4WXYUHAMXUJRVDXI2YKHANCNFSM6AAAAAAYST5UHY>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>