add taraxa custom domain
snapshot-labs/snapshot-spaces pull request #2481
Opened 2023-06-09 12:37 UTC by VargaElod23

#### Hi! What is your PR about?

- [x] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-06-12 01:22 UTC, gokaiorg requested changes
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.org/#/taraxa-project.eth

2023-06-12 07:28 UTC, VargaElod23 commented
Hi @gokaiorg . Yeah, we're still finalizing the economical details of the strat, so I'll leave a tag here once the strategy and space is finished. Thanks for taking a look here!

2023-06-14 14:33 UTC, VargaElod23 commented
Hi @gokaiorg . We registered a dummy space at https://snapshot.org/#/taraxa-project.eth. I also made sure that all the other steps are there. Here are the PRs:

- Network addition: https://github.com/snapshot-labs/snapshot.js/pull/847
- This one for skin and domain
- Strategy: https://github.com/snapshot-labs/snapshot-strategies/pull/1190

Strategy tests need the network addition. Can you take a look? Thanks

2023-06-15 04:39 UTC, gokaiorg requested changes

2023-06-15 04:39 UTC, gokaiorg commented on skins/index.js
> +import taraxa from "./taraxa.scss";
You will also need to add your skin in the `export default` index.js line 303

2023-06-16 10:15 UTC, gokaiorg approved these changes

2023-06-16 10:15 UTC, merged

2023-06-20 02:03 UTC, manny861 commented
0x3b484b82567a09e2588A13D54D032153f0c0aEe0