add eazyswap domain
snapshot-labs/snapshot-spaces pull request #2489
Opened 2023-07-02 18:48 UTC by theeazyswap

#### Hi! What is your PR about?

Add new domain for eazyswap.eth

2023-07-03 02:26 UTC, gokaiorg requested changes

2023-07-03 02:26 UTC, gokaiorg commented on spaces/domains.json
> +  "gov.eazyswap.io":"eazyswap.eth",
You will need to add a space between your sub domain and ENS value.
```suggestion
  "gov.eazyswap.io": "eazyswap.eth",
```

2023-07-03 11:36 UTC, theeazyswap commented
updated with the suggestion.

2023-07-05 03:43 UTC, gokaiorg approved these changes

2023-07-05 03:43 UTC, merged