Update domains.json
snapshot-labs/snapshot-spaces pull request #2510
Opened 2023-08-29 22:20 UTC by skylordafk

Alriiight, let's try this again.

I created this new space using a wallet that holds the corresponding ENS. I hope this is the correct formatting.

2023-08-30 07:58 UTC, gokaiorg requested changes

2023-08-30 07:58 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.daocred.xyz": "daocred.eth"
A comma is missing at the end of the line of your sub-domain.
```suggestion
  "vote.daocred.xyz": "daocred.eth",
```

2023-09-01 17:51 UTC, skylordafk commented
Just committed the change @gokaiorg

2023-09-02 03:56 UTC, gokaiorg approved these changes

2023-09-02 03:57 UTC, merged