Add Dexilla protocol
snapshot-labs/snapshot-spaces pull request #2516
Opened 2023-09-04 04:07 UTC by curbisn

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [x] Add an alias to migrate your space

2023-09-05 04:35 UTC, gokaiorg requested changes

2023-09-05 04:35 UTC, gokaiorg commented on spaces/aliases.json
> +  "dexilla": "dexilla.eth",
You will not need to edit the aliases.json file for a space creation. 
### 
```suggestion
```

2023-09-05 05:11 UTC, curbisn commented
@gokaiorg I've removed the alias, please recheck - thanks

2023-09-06 03:00 UTC, gokaiorg approved these changes

2023-09-06 03:00 UTC, merged