Add PillarDAO custom domain
snapshot-labs/snapshot-spaces pull request #2523
Opened 2023-09-25 16:48 UTC by arddluma

#### Hi! What is your PR about?
Added https://pillardao.org/ for https://snapshot.org/#/plrdao.eth 

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-09-28 02:42 UTC, gokaiorg requested changes

2023-09-28 02:42 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.pillardao.org": "plrdao.eth",
You will need to remove the comma at the end of the line of your sub-domain.
```suggestion
  "vote.pillardao.org": "plrdao.eth"
```

2023-10-02 11:18 UTC, arddluma commented on spaces/domains.json
> +  "vote.pillardao.org": "plrdao.eth",
hello, Thank you.
Could you please re-review.

2023-10-03 03:26 UTC, gokaiorg approved these changes

2023-10-03 03:28 UTC, merged