add emcdao.eth custom domain
snapshot-labs/snapshot-spaces pull request #2533
Opened 2023-10-03 17:00 UTC by EMCprotocol

add emcdao.eth custom domain with "vote.edgematrix.pro"

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

2023-10-04 07:43 UTC, gokaiorg requested changes

2023-10-04 07:43 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.edgematrix.pro":"emcdao.eth",
### You will need to add a space here.
```suggestion
  "vote.edgematrix.pro": "emcdao.eth",
```

2023-10-04 09:24 UTC, EMCprotocol commented on spaces/domains.json
> +  "vote.edgematrix.pro":"emcdao.eth",
done , thanks ~

2023-10-05 03:03 UTC, gokaiorg approved these changes

2023-10-05 03:04 UTC, merged