Update domains.json
snapshot-labs/snapshot-spaces pull request #2540
Opened 2023-10-30 11:04 UTC by ReformDAO

Added vote.reformdao.com

2023-10-31 04:22 UTC, gokaiorg requested changes

2023-10-31 04:22 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.reformdao.com": "rfrmdao.eth"
A comma is missing at the end of the line above your sub-domain.
```suggestion
  "vote.gamedao.co": "gamedao.eth",
  "vote.reformdao.com": "rfrmdao.eth"
```

2023-11-06 16:47 UTC, ReformDAO commented
Could you please approve, i changed everything requested?

2023-11-09 10:00 UTC, wa0x6e approved these changes
utAck

2023-11-09 10:01 UTC, merged