Update domains.json
snapshot-labs/snapshot-spaces pull request #2572
Opened 2024-03-09 07:45 UTC by Builder0x

Added line 14
"vote.refluid.net": "refluid.eth",

#### Hi! What is your PR about?
- Add a custom domain for your space

2024-03-09 12:30 UTC, ChaituVR requested changes

2024-03-09 12:30 UTC, ChaituVR commented on spaces/domains.json
> +  "vote.refluid.net": "refluid.eth",
I see 
![image](https://github.com/snapshot-labs/snapshot-spaces/assets/15967809/1f41e82e-4c6d-4286-a436-669c7bd891e0)

Any idea?

2024-03-10 16:41 UTC, Builder0x commented on spaces/domains.json
> +  "vote.refluid.net": "refluid.eth",
Sloved, Please check again

2024-03-10 17:22 UTC, ChaituVR requested changes

2024-03-10 17:22 UTC, ChaituVR commented on spaces/domains.json
> +  "vote.refluid.net": "refluid.eth",
<img width="710" alt="image" src="https://github.com/snapshot-labs/snapshot-spaces/assets/15967809/2ad10ca8-eda2-410f-a6ff-9ce52d27067d">
Not working too

Looks like there is no CNAME at all 
<img width="1202" alt="image" src="https://github.com/snapshot-labs/snapshot-spaces/assets/15967809/a386f6cc-3022-4ffc-b039-ff113558b1b6">

2024-03-11 05:21 UTC, Builder0x commented on spaces/domains.json
> +  "vote.refluid.net": "refluid.eth",
oh sorry
We added the CNAME
Please check again

2024-03-11 05:36 UTC, ChaituVR approved these changes

2024-03-11 05:36 UTC, merged