Add INDEX space
snapshot-labs/snapshot-spaces pull request #258
Opened 2020-10-14 20:59 UTC by inje

**Add space for Index Coop**  
  
Etherscan: https://etherscan.io/address/0x0954906da0Bf32d5479e25f46056d22f08464cab
CoinGecko: https://www.coingecko.com/en/coins/index-cooperative
Website: https://www.indexcoop.com/
Twitter: https://twitter.com/indexcoop

2020-10-15 01:37 UTC, e-asia requested changes
You have some extra fields in your `index.json` file and your `skin.scss` has to be moved to the `skins` directory, the space creating process has been updated, you have to follow the new documentation. https://docs.snapshot.page/guides/create-a-space

2020-10-15 01:40 UTC, inje commented
@e-asia Thanks for the reply. Which fields are the extra fields that should be removed?

2020-10-15 02:13 UTC, e-asia commented
> @e-asia Thanks for the reply. Which fields are the extra fields that should be removed?

The `key` and `address` fields should be removed and the `skin` field is missing. Take a look on the sample file https://docs.snapshot.page/guides/create-a-space#3-change-your-space-metadata

2020-10-15 14:36 UTC, e-asia requested changes

2020-10-15 14:36 UTC, e-asia commented on spaces/index/index.json
> +  ]
This is the default strategies and it's useless to add it now, you should remove it.

2020-10-15 17:31 UTC, inje commented on spaces/index/index.json
> +  ]
Okay 👌. Updated

2020-10-16 01:26 UTC, e-asia approved these changes

2020-10-16 02:05 UTC, merged