Add SWAGG space
snapshot-labs/snapshot-spaces pull request #273
Opened 2020-10-15 16:23 UTC by thisiscarlosgomes

Add space for SWAGG
  
Etherscan: https://etherscan.io/token/0xa19A40FbD7375431fAB013a4B08F00871B9a2791
CoinGecko: https://www.coingecko.com/en/coins/swagg-network
Website: https://swagg.network
Twitter: https://twitter.com/swaggntwk

2020-10-16 02:01 UTC, e-asia requested changes

2020-10-16 02:01 UTC, e-asia commented on skins/swagg.scss
> +  }
Please use only theme variables. No extra custom styles are allowed.

2020-10-16 02:39 UTC, thisiscarlosgomes commented on skins/swagg.scss
> +  }
This is the same extra style used by https://snapshot.page/#/aave or https://snapshot.page/#/aavegotchi

2020-10-16 18:39 UTC, thisiscarlosgomes reviewed
Fixed

2020-10-17 02:52 UTC, e-asia approved these changes

2020-10-17 02:52 UTC, merged