Web3API Snapshot Space
snapshot-labs/snapshot-spaces pull request #281
Opened 2020-10-16 17:38 UTC by dOrgJelli

**Add space for Web3API**  
  
Etherscan: https://etherscan.io/token/0x9F59E5Ed123C10D57E92629612511b14628D2799
Website: http://web3api.dev/
Twitter: https://twitter.com/web3api

2020-10-17 02:43 UTC, e-asia requested changes

2020-10-17 02:43 UTC, e-asia commented on skins/web3-api.scss
> +  }
Please use only theme variables. No extra custom styles are allowed.

2020-10-18 23:20 UTC, dOrgJelli commented
Fixed @gokaiorg

2020-10-19 01:45 UTC, gokaiorg approved these changes

2020-10-19 01:46 UTC, merged