Add UniCore Space
snapshot-labs/snapshot-spaces pull request #297
Opened 2020-10-20 05:53 UTC by QuantSoldier

https://uvault.finance/

https://etherscan.io/token/0x5506861bbb104Baa8d8575e88E22084627B192D8

**Add space for UniCore**  
  
Etherscan: https://etherscan.io/address/0x5506861bbb104Baa8d8575e88E22084627B192D8  
CoinGecko: Application Pending (https://www.coingecko.com/en/coins/unicorn)
Website: https://uvault.finance
Twitter: https://twitter.com/uvault_finance

Uniswap Info Page for further verification: https://info.uniswap.org/token/0x5506861bbb104Baa8d8575e88E22084627B192D8

2020-10-20 11:11 UTC, gokaiorg requested changes

2020-10-20 11:11 UTC, gokaiorg commented on spaces/unicore/index.json
> +        "symbol": "UNICORE"
Decimal field is missing.
```suggestion
        "symbol": "UNICORE",
        "decimals": 18
```

2020-10-20 18:16 UTC, QuantSoldier commented on spaces/unicore/index.json
> +        "symbol": "UNICORE"
Updated w/ the change :)

2020-10-21 02:17 UTC, gokaiorg approved these changes

2020-10-21 02:17 UTC, gokaiorg commented on spaces/unicore/index.json
> +        "decimals": 18,
Please just remove comma and we are done! 
```suggestion
        "decimals": 18
```

2020-10-23 01:36 UTC, gokaiorg approved these changes

2020-10-23 01:55 UTC, merged