added CARTEL
snapshot-labs/snapshot-spaces pull request #315
Opened 2020-10-21 14:29 UTC by besoeasy

**Add space for CARTEL**  
  
Etherscan: https://etherscan.io/token/0x9257e8c80119fedab64842024ced4113912b0ab1
Website: https://cashcartel.eth/
Twitter: https://twitter.com/cashcarteleth

2020-10-21 16:03 UTC, gokaiorg requested changes
The images file size should not exceed 50KB. Please reduce their weight.

2020-10-21 16:03 UTC, gokaiorg commented on spaces/cartel/index.json
> +  "skin": "example",
If you use the default theme you will have to remove the skin field.

2020-10-21 17:07 UTC, besoeasy commented
@gokaiorg fixed, thanks for your time

2020-10-22 01:14 UTC, gokaiorg approved these changes

2020-10-22 01:28 UTC, merged