Add ZZZ space
snapshot-labs/snapshot-spaces pull request #316
Opened 2020-10-21 16:08 UTC by Tranquil-Flow

Add space for ...

Etherscan: https://etherscan.io/address/0xc75f15ada581219c95485c578e124df3985e4ce0
CoinGecko: https://www.coingecko.com/en/coins/zzz-finance
Website: https://zzz.finance/
Twitter: https://twitter.com/zzzfinance

2020-10-21 16:53 UTC, gokaiorg requested changes
Your images directory name is wrong. You should replace `spaces/ZZZ.finance/logo.png` and `spaces/ZZZ.finance/space.png` by ` spaces/zzz-finance/logo.png` and `spaces/zzz-finance/space.png`.

2020-10-21 16:53 UTC, gokaiorg commented on spaces/zzz-finance/index.json
> +  "domain": "https://zzz.finance/",
Use the domain field to add a subdomain if you have one or you should delete this field.
```suggestion
```

2020-10-21 16:55 UTC, gokaiorg commented on spaces/zzz-finance/index.json
> +  "domain": "https://zzz.finance/",
You should also delete the `"skin": "example",` field if you use the default skin.

2020-10-22 08:49 UTC, Tranquil-Flow commented
@gokaiorg, made the changes as requested. Let me know if there is any further issues!

2020-10-22 11:35 UTC, gokaiorg approved these changes

2020-10-22 11:41 UTC, merged