adding decentribe space
snapshot-labs/snapshot-spaces pull request #339
Opened 2020-10-23 20:31 UTC by lucan-decentribe

**Add space for ...**  
  
Etherscan: https://etherscan.io/address/...  
CoinGecko: https://www.coingecko.com/en/coins/...  
Website: https://...  
Twitter: https://twitter.com/...

2020-10-24 02:40 UTC, gokaiorg requested changes

2020-10-24 02:40 UTC, gokaiorg commented on spaces/decentribe/index.json
> +  "token": "0x900B1998A226CFE238Ba1a14F03eB934C513C20B",
You will miss the `strategies` field.
```suggestion
  "token": "0x900B1998A226CFE238Ba1a14F03eB934C513C20B",
  "strategies": [
    {
      "name": "erc20-balance-of",
      "params": {
        "address": "0x900B1998A226CFE238Ba1a14F03eB934C513C20B",
        "symbol": "DECENT",
        "decimals": 18
      }
    }
  ],
```

2020-10-27 09:39 UTC, lucan-decentribe commented
added the requested changed, please review again

2020-10-27 11:53 UTC, gokaiorg approved these changes

2020-10-27 11:56 UTC, merged