Add ETGF space
snapshot-labs/snapshot-spaces pull request #342
Opened 2020-10-24 02:56 UTC by EthereumGoldETG

Add space for ETGF

Etherscan: https://etherscan.io/token/0x74603e780545d02C4257E7D2BE19c74dE7BE1952
CoinGecko: Application Pending (https://www.coingecko.com/en/coins/etg-finance)
Website: https://etgproject.org
Twitter: https://twitter.com/ethereumgoldetg

2020-10-24 03:05 UTC, gokaiorg requested changes
You should rename your space directory, uppercase are not allowed.
`spaces/ETG.Finance/...` to `spaces/etgfinance/...`

2020-10-24 03:05 UTC, gokaiorg commented on spaces/ETG.Finance/index.json
> +  ]
The `invalids` field should be move in `filters`.
```suggestion
  "filters": { 
    "defaultTab": "all", 
    "minScore": 0.01, 
    "onlyMembers": true,
    "invalids": [ 
      "0x6a36222e45265640B636e6BD2b558d1fB81458E6" 
    ]
  }
```

2020-10-24 03:26 UTC, EthereumGoldETG commented
Name updated

On Sat, Oct 24, 2020, 04:05 Gokai <notifications@github.com> wrote:

> *@gokaiorg* requested changes on this pull request.
>
> You should rename your space directory, uppercase are not allowed.
> spaces/ETG.Finance/... to spaces/etgfinance/...
> ------------------------------
>
> In spaces/ETG.Finance/index.json
> <https://github.com/snapshot-labs/snapshot-spaces/pull/342#discussion_r511278674>
> :
>
> > +  "filters": {
>
> +    "defaultTab": "all",
>
> +    "minScore": 0.01,
>
> +    "onlyMembers": true
>
> +  },
>
> +  "invalids": [
>
> +    "0x6a36222e45265640B636e6BD2b558d1fB81458E6"
>
> +  ]
>
>
> The invalids field should be move in filters.
> ⬇️ Suggested change
>
> -  "filters": {
>
> -    "defaultTab": "all",
>
> -    "minScore": 0.01,
>
> -    "onlyMembers": true
>
> -  },
>
> -  "invalids": [
>
> -    "0x6a36222e45265640B636e6BD2b558d1fB81458E6"
>
> -  ]
>
> +  "filters": {
>
> +    "defaultTab": "all",
>
> +    "minScore": 0.01,
>
> +    "onlyMembers": true,
>
> +    "invalids": [
>
> +      "0x6a36222e45265640B636e6BD2b558d1fB81458E6"
>
> +    ]
>
> +  }
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/snapshot-labs/snapshot-spaces/pull/342#pullrequestreview-516153655>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG3JOXQMGVC37RCJE4OTE4LSMI77JANCNFSM4S5INNVQ>
> .
>

2020-10-25 02:51 UTC, gokaiorg approved these changes

2020-10-25 03:08 UTC, merged