Add zacfinance space
snapshot-labs/snapshot-spaces pull request #350
Opened 2020-10-25 18:51 UTC by ZAC-FINANCE

**Add space for ZACFinance**  
  
Etherscan: https://etherscan.io/token/0x98a90499b62Ae48E151a66B0F647570b5a473B1c
CoinGecko: https://www.coingecko.com/en/coins/zac-finance 
Website: https://zac.finance/  
Twitter: https://twitter.com/FinanceZac

2020-10-26 06:17 UTC, gokaiorg approved these changes

2020-10-26 06:17 UTC, gokaiorg commented on spaces/zacfinance/index.json
> +  "domain": "governance.zac.finance",
If you want to add custom styles, please add your custom colours in `skins/zacfinance.scss` or delete `skin` field from `index.json` file to use default skin. 
If you want to add a custom domain, please add your custom domain in `spaces/domains.json` or delete `domain` field from `index.json` file.

2020-10-26 19:00 UTC, ZAC-FINANCE commented on spaces/zacfinance/index.json
> +  "domain": "governance.zac.finance",
done, check again.

2020-10-27 11:39 UTC, gokaiorg requested changes

2020-10-27 11:39 UTC, gokaiorg commented on spaces/zacfinance/index.json
> +  "domain": "",
Delete completely this 2 lines.

2020-10-27 18:41 UTC, ZAC-FINANCE commented on spaces/zacfinance/index.json
> +  "domain": "",
done, check again.

Thanks.

2020-10-28 02:55 UTC, gokaiorg approved these changes

2020-10-28 03:10 UTC, merged