Add custom domain to tballiance
snapshot-labs/snapshot-spaces pull request #354
Opened 2020-10-26 03:19 UTC by emn178

Add custom domain to tballiance

2020-10-26 06:25 UTC, gokaiorg requested changes

2020-10-26 06:25 UTC, gokaiorg commented on spaces/tballiance/index.json
> +  "domain": "tbavote.joyso.io",
To add a custom domain you will need to add your domain in `spaces/domains.json` file also.

2020-10-26 06:25 UTC, gokaiorg commented on skins/tballiance.scss
> +  }
Please use only theme variables. No extra custom styles are allowed.

2020-11-01 02:37 UTC, emn178 commented on skins/tballiance.scss
> +  }
but no variable to change button background

2020-11-01 10:22 UTC, gokaiorg commented
We've made a major global update, please pull before commit again your changes.
You can use the documentation to help you.
https://docs.snapshot.page/guides/create-a-space#1-fork-snapshot-spaces-repository-here

2020-11-02 03:55 UTC, gokaiorg approved these changes

2020-11-02 04:05 UTC, merged