Add Tokenlon space
snapshot-labs/snapshot-spaces pull request #355
Opened 2020-10-26 04:21 UTC by BenjaminLu

Tokenlon Website: https://tokenlon.im/instant
TFT Token Contract: https://etherscan.io/token/0xe534619defdbf0caf673b8abf7158714f5bd4bd9

**Add space for Tokenlon**  
  
Etherscan: https://etherscan.io/address/0xe534619defdbf0caf673b8abf7158714f5bd4bd9
CoinGecko: https://www.coingecko.com/en/exchanges/tokenlon
Website: https://tokenlon.im
Twitter: https://twitter.com/tokenlon

Github: https://github.com/consenlabs
Medium: https://medium.com/imtoken

2020-10-26 06:33 UTC, gokaiorg requested changes

2020-10-26 06:33 UTC, gokaiorg commented on skins/tokenlon.scss
> +}
If you use the default theme you will have to delete the scss file.

2020-10-26 06:33 UTC, gokaiorg commented on spaces/tokenlon/index.json
> +  "skin": "tokenlon",
If you use the default theme you will have to remove the skin field.

2020-10-26 09:56 UTC, bonustrack commented on spaces/tokenlon/index.json
> +      "name": "tokenlon",
This should be changed
```suggestion
      "name": "erc20-with-balance",
```

2020-10-26 09:57 UTC, bonustrack commented on spaces/tokenlon/index.json
> +  "invalids": []
Invalids should be in "filters" but it's not necessary to add it if its empty.

2020-10-27 03:04 UTC, BenjaminLu commented
Done. Much appreciated!

2020-10-27 06:23 UTC, bonustrack approved these changes

2020-10-27 06:23 UTC, merged