Update LexDAO space (token)
snapshot-labs/snapshot-spaces pull request #365
Opened 2020-10-28 00:23 UTC by Ro5s

update dao token reference to 0x4053981a40836141Cb79F05f68E9da385ff1814E

2020-10-28 00:31 UTC, Ro5s commented
also, if possible, how might I include update logo.png - https://imgur.com/gallery/fRrvQGJ ?

2020-10-28 03:01 UTC, gokaiorg commented
> also, if possible, how might I include updated logo.png - https://imgur.com/gallery/fRrvQGJ ?

Replace them on your local fork folder and commit the changes. You can use doc to see how update your local fork https://docs.snapshot.page/guides/create-a-space#1-fork-snapshot-spaces-repository-here

2020-10-28 03:02 UTC, gokaiorg approved these changes

2020-10-28 03:02 UTC, gokaiorg commented on spaces/lexdao/index.json
> +  "token": "0x4053981a40836141Cb79F05f68E9da385ff1814E",
If you change the base token address your old proposals will not be visible anymore under your space, are you sure you want to go forward with this?

2020-10-31 09:55 UTC, gokaiorg commented on spaces/lexdao/index.json
> +  "token": "0x4053981a40836141Cb79F05f68E9da385ff1814E",
We are doing some changes for spaces settings, you can change your strategy token if you want but the root token value must stay like that.

2020-11-01 10:17 UTC, gokaiorg requested changes
We've made a major global update, please pull before commit again your changes.
You can use the documentation to help you.
https://docs.snapshot.page/guides/create-a-space#1-fork-snapshot-spaces-repository-here

2020-11-04 11:54 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-11-04 11:54 UTC, closed without merging