Update zzz, add invalids
snapshot-labs/snapshot-spaces pull request #368
Opened 2020-10-28 06:33 UTC by Tranquil-Flow

Looking to add several test proposals to the invalids list so they are filtered out

2020-10-29 03:35 UTC, gokaiorg requested changes

2020-10-29 03:35 UTC, gokaiorg commented on spaces/zzz-finance/index.json
>      "onlyMembers": false
You will miss a comma here.
```suggestion
    "onlyMembers": false,
```

2020-10-29 04:00 UTC, Tranquil-Flow commented on spaces/zzz-finance/index.json
>      "onlyMembers": false
> You will miss a comma here.

Edited to include comma

2020-10-29 04:32 UTC, Tranquil-Flow commented on spaces/zzz-finance/index.json
>      "onlyMembers": false
Also, I think your Gitbook needs to be updated, in the example used demonstrating how to add a space, there is no comma after the onlyMembers parameter input. https://docs.snapshot.page/guides/create-a-space

2020-10-30 02:06 UTC, gokaiorg approved these changes

2020-10-30 02:08 UTC, merged