Add DATA space
snapshot-labs/snapshot-spaces pull request #374
Opened 2020-10-28 17:06 UTC by hpihkala

**Add space for Streamr (DATA)**  
  
Etherscan: https://etherscan.io/address/0x0cf0ee63788a0849fe5297f3407f701e122cc023
CoinGecko: https://www.coingecko.com/en/coins/streamr-datacoin
Website: https://streamr.network
Twitter: https://twitter.com/streamr

**Notes**

Really nice tool guys, we'd like to do a governance pilot on it. Can't wait!

Didn't tweak the default/example skin yet, but added the style file as a placeholder for further improvement.

2020-10-29 03:44 UTC, gokaiorg requested changes

2020-10-29 03:44 UTC, gokaiorg commented on skins/streamr.scss
> +}
If you use the default theme you will have to delete the scss file.

2020-10-29 03:44 UTC, gokaiorg commented on spaces/streamr/index.json
> +  "skin": "streamr",
If you use the default theme you will have to remove the skin field.

2020-10-29 13:37 UTC, hpihkala commented
Our designers wanted to customize the skin a little bit but not too much, updated in the latest commit.

2020-10-30 01:41 UTC, gokaiorg approved these changes

2020-10-30 02:07 UTC, merged