Add EDI Space
snapshot-labs/snapshot-spaces pull request #375
Opened 2020-10-28 19:18 UTC by sambacha

**Add space for ... Freight Trust Network $EDI** 

> we are renaming the network to 'as2.network' , 

Etherscan: https://etherscan.io/token/0x79C5a1Ae586322A07BfB60be36E1b31CE8C84A1e  
CoinGecko: https://www.coingecko.com/en/coins/freight-trust-network  
Website: https://freighttrust.com  
Twitter: https://twitter.com/freighttrustnet

\[as2.network\](https://as2.network)

\<3

2020-10-29 03:46 UTC, gokaiorg requested changes
You will want to add `logo.png` and `space.png` images.
https://docs.snapshot.page/guides/create-a-space#4-add-a-logo-and-space-images

2020-10-29 08:05 UTC, sambacha commented
Fixed,  must have mistaken them as optional

2020-10-29 08:16 UTC, bonustrack commented on spaces/edi/index.json
> +        "symbol": "evo[a-z,A-Z,0-9]",
Can you confirm the address and symbol are correct? This seem to be aLEND token.

2020-10-29 08:16 UTC, bonustrack commented on spaces/edi/index.json
> +  "skin": "edi",
The skin should exist here: https://github.com/snapshot-labs/snapshot-spaces/tree/master/skins

2020-11-01 10:10 UTC, gokaiorg requested changes
We've made a major global update, please pull before commit again your changes.
You can use the documentation to help you.
https://docs.snapshot.page/guides/create-a-space#1-fork-snapshot-spaces-repository-here

2020-11-06 01:57 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-11-06 01:57 UTC, closed without merging