Add DIAData
snapshot-labs/snapshot-spaces pull request #384
Opened 2020-10-29 17:24 UTC by bitsandtea

Etherscan: https://etherscan.io/token/0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419
CoinGecko: https://www.coingecko.com/en/coins/dia
Website: https://diadata.org
Twitter: https://twitter.com/DIAdata_org

Great tool, looking forward to our first vote! We might change the skins later. Thanks

2020-10-30 01:53 UTC, gokaiorg requested changes

2020-10-30 01:53 UTC, gokaiorg commented on skins/diadata.scss
> +    --bg-color: CCE0F4;
You miss a #. 
```suggestion
    --bg-color: #CCE0F4;
```

2020-10-30 01:53 UTC, gokaiorg commented on spaces/diadata/index.json
> +  "domain": "vote.diadata.org",
You will need `skin` field to add your custom styles.
```suggestion
  "skin": "diadata",
  "domain": "vote.diadata.org",
```

2020-10-30 01:55 UTC, gokaiorg commented on spaces/diadata/index.json
> +  "domain": "vote.diadata.org",
To add your custom domain you will have to add your domain in `spaces/domains.json` file also.
https://docs.snapshot.page/guides/custom-domain

2020-10-30 09:32 UTC, bitsandtea commented on spaces/diadata/index.json
> +  "domain": "vote.diadata.org",
Added, thanks

2020-10-30 09:32 UTC, bitsandtea commented on skins/diadata.scss
> +    --bg-color: CCE0F4;
Added, thanks

2020-10-31 09:34 UTC, gokaiorg approved these changes

2020-10-31 09:35 UTC, gokaiorg commented
The file `spaces/domains.json` has been updated since your last commit, you should checkout this file and commit again your changes. Thank you.

2020-10-31 10:22 UTC, bitsandtea commented
> The file `spaces/domains.json` has been updated since your last commit, you should checkout this file and commit again your changes. Thank you.

just re-committed it!

2020-10-31 12:32 UTC, merged