update DANIMESQ-xdai space
snapshot-labs/snapshot-spaces pull request #390
Opened 2020-10-30 05:52 UTC by DaniellMesquita

Signed-off-by: Daniell Mesquita <daniellmesquita@protonmail.com>

**Add space for ...**  
  
Etherscan: https://etherscan.io/address/...  
CoinGecko: https://www.coingecko.com/en/coins/...  
Website: https://...  
Twitter: https://twitter.com/...

2020-10-31 09:17 UTC, gokaiorg requested changes

2020-10-31 09:17 UTC, gokaiorg commented on spaces/daniell-mesquita-xdai/index.json
> +  "token": "0x95d7C55C260c18d0E7705236773C0b7942e1a0bF",
We are doing some changes for spaces settings, you can change your strategy token if you want but the root token value must stay like that.

2020-11-01 10:11 UTC, gokaiorg requested changes
We've made a major global update, please pull before commit again your changes.
You can use the documentation to help you.
https://docs.snapshot.page/guides/create-a-space#1-fork-snapshot-spaces-repository-here

2020-11-06 01:57 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-11-06 01:57 UTC, closed without merging

2021-01-07 21:11 UTC, DaniellMesquita commented
So, root address is same from Layer1 token address?