Add PRIA space
snapshot-labs/snapshot-spaces pull request #401
Opened 2020-10-30 20:12 UTC by dahifi

**Add space for PRIA **  
  
Etherscan: https://etherscan.io/address/0xb9871cb10738eada636432e86fc0cb920dc3de24
CoinGecko: https://www.coingecko.com/en/coins/pria
Website: https://pria.network/
Twitter: https://twitter.com/defi_labs_

2020-10-31 09:37 UTC, gokaiorg requested changes

2020-10-31 09:37 UTC, gokaiorg commented on skins/pria.scss
> +}
If you use the default theme you will have to delete the scss file.

2020-10-31 09:37 UTC, gokaiorg commented on spaces/pria/index.json
> +  "skin": "pria",
If you use the default theme you will have to remove the skin field.

2020-11-01 10:13 UTC, gokaiorg requested changes
We've made a major global update, please pull before commit again your changes.
You can use the documentation to help you.
https://docs.snapshot.page/guides/create-a-space#1-fork-snapshot-spaces-repository-here

2020-11-01 10:16 UTC, gokaiorg commented
Your PR seem to be a duplicate with #406

2020-11-01 11:01 UTC, dahifi commented
@gokaiorg, I merged your global commits and removed the default scss templates from both locations. We should be G2G, and will get with our team on cancelling https://github.com/snapshot-labs/snapshot-spaces/pull/406

Thanks!

2020-11-01 15:30 UTC, bonustrack commented on spaces/pria/index.json
> +  "name": "PRIA ",
```suggestion
  "name": "PRIA",
```

2020-11-01 15:31 UTC, merged