Add space for Rari Capital
snapshot-labs/snapshot-spaces pull request #403
Opened 2020-10-31 22:12 UTC by davidlucid

**Add space for Rari Capital**

Can someone please confirm that the displayed RGT voter scores/shares/balances will be the sum of the RGT balances returned by the two strategies (`erc20-balance-of` and `rari-unclaimed-rgt`)? Or should I write a single strategy to combine the two?

Thank you so much!!!
  
Etherscan: https://etherscan.io/address/0xD291E7a03283640FDc51b121aC401383A46cC623
CoinGecko: https://www.coingecko.com/en/coins/rari-governance-token
Website: http://rari.capital/
Twitter: https://twitter.com/RariCapital

2020-11-01 01:33 UTC, gokaiorg requested changes
The space doesn’t load properly with this strategies.
@bonustrack Could you review it? Thank you.

2020-11-01 01:35 UTC, gokaiorg requested changes

2020-11-01 01:35 UTC, gokaiorg commented on spaces/rari/index.json
> +  "domain": "vote.rari.capital",
To add a custom domain you will have to add your domain in this file https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json

2020-11-01 06:08 UTC, davidlucid commented on spaces/rari/index.json
> +  "domain": "vote.rari.capital",
Done!

2020-11-01 07:39 UTC, davidlucid commented
@gokaiorg Added to domains.json!

2020-11-01 10:01 UTC, gokaiorg commented
We've made a major global update, please pull before commit again your changes. Thank you.

2020-11-02 00:15 UTC, davidlucid commented
@gokaiorg I have pulled the latest changes and updated my index.json!

2020-11-02 00:17 UTC, davidlucid commented
Link to strategy pull request: https://github.com/snapshot-labs/snapshot.js/pull/25

2020-11-02 04:53 UTC, bonustrack commented on spaces/rari/index.json
> +      "name": "rari-unclaimed-rgt",
@davidlucid Your PR looks good, i would just suggest to use "contract-call" strategy here, i've sent a comment in the strategy PR: https://github.com/snapshot-labs/snapshot.js/pull/25#issuecomment-720234232 let me know if need more info.

2020-11-02 08:10 UTC, davidlucid commented
Now using `contract-call`! @bonustrack

2020-11-02 09:53 UTC, bonustrack approved these changes
Looks good!

2020-11-02 09:54 UTC, merged