Update DIAData Space
snapshot-labs/snapshot-spaces pull request #420
Opened 2020-11-04 10:01 UTC by bitsandtea

Update our space to include:

- New strategy
- new css
- invalidate a proposal

Etherscan: https://etherscan.io/token/0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419
CoinGecko: https://www.coingecko.com/en/coins/dia
Website: https://diadata.org
Twitter: https://twitter.com/DIAdata_org

2020-11-04 10:06 UTC, gokaiorg requested changes

2020-11-04 10:06 UTC, gokaiorg commented on spaces/diadata/index.json
> +    "invalids": [ // List of proposals IDs (use this to remove a proposal from your space)
JSON standard does not allow comments. Please remove them.

2020-11-04 10:06 UTC, gokaiorg commented on spaces/diadata/index.json
> +  "token": "0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419",
Please remove this field, we don't use it anymore.

2020-11-04 10:06 UTC, gokaiorg commented on skins/diadata.scss
> +  }
Please use one space per css file.
```suggestion
.diadata {
    --primary-color: #4f33ff;
    --bg-color: #141414;
    --text-color: #CCE0F4;
    --link-color: #ff7096;
    --heading-color: #CCE0F4;
    --border-color: #00CCB7;
  }
```

2020-11-04 10:18 UTC, bitsandtea commented on spaces/diadata/index.json
> +  "token": "0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419",
Done!

2020-11-04 10:18 UTC, bitsandtea commented on spaces/diadata/index.json
> +    "invalids": [ // List of proposals IDs (use this to remove a proposal from your space)
Done!

2020-11-04 10:18 UTC, bitsandtea commented on skins/diadata.scss
> +  }
Done!

2020-11-04 11:52 UTC, gokaiorg commented
There is a conflict in your PR, can you resolve it?

2020-11-04 14:47 UTC, bitsandtea commented
> There is a conflict in your PR, can you resolve it?

Yes, just did. Thanks

2020-11-04 14:52 UTC, gokaiorg requested changes

2020-11-04 14:52 UTC, gokaiorg commented on spaces/domains.json
>    "vote.diadata.org": "diadata",
You have added your domain twice and a comma is missing. Please correct this file.

2020-11-04 14:55 UTC, gokaiorg commented
Related to https://github.com/snapshot-labs/snapshot.js/pull/28

2020-11-04 15:12 UTC, bitsandtea commented on spaces/domains.json
>    "vote.diadata.org": "diadata",
Arghh, sorry for that. Fixed.

2020-11-07 09:59 UTC, bonustrack commented on spaces/diadata/index.json
> +          "minTokenBalance": 10
I've done some change so you can use an existing strategy 'erc20-with-balance' using 'minBalance' see an example of the params here: https://github.com/snapshot-labs/snapshot.js/commit/6cbeec432c85aaed002d3543b5335983b7b0a58b#diff-1b836984505debc8fc7aa0ae1af07c1364c6ba9cf70060d53c2c2aaab096dfbcR28-R34

2020-11-07 10:48 UTC, bitsandtea reviewed
Yes that works

2020-11-07 14:01 UTC, gokaiorg requested changes
You should not add `spaces/domains.json` in your PR.

2020-11-07 14:01 UTC, gokaiorg commented on spaces/diadata/index.json
> +          "minTokenBalance": 10
```suggestion
          "minBalance": 10
```

2020-11-07 14:01 UTC, gokaiorg commented on spaces/diadata/index.json
> +      "name": "erc20-balance-of-minimum",
`erc20-balance-of-minimum` is not an existing strategy. You could use an existing one https://github.com/snapshot-labs/snapshot.js/tree/master/src/strategies
```suggestion
      "name": "erc20-with-balance",
```

2020-11-07 18:08 UTC, bitsandtea commented
@gokaiorg I just accepted your commits for the strategy name. In terms of not adding the domains file I am not sure what you mean? There is a requirement to add [it here](https://docs.snapshot.page/guides/custom-domain).

We have a PR coming out this Monday so we would really appreciate if we have this approved by then. Thanks!

2020-11-08 05:48 UTC, gokaiorg commented
> @gokaiorg I just accepted your commits for the strategy name. In terms of not adding the domains file I am not sure what you mean? There is a requirement to add [it here](https://docs.snapshot.page/guides/custom-domain).
> 
> We have a PR coming out this Monday so we would really appreciate if we have this approved by then. Thanks!

Yes you are right but you already add it and it's live. You are committing it again without changes. https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json#L36

2020-11-08 05:51 UTC, gokaiorg approved these changes

2020-11-08 05:54 UTC, merged