Add space for MANTRA DAO
snapshot-labs/snapshot-spaces pull request #423
Opened 2020-11-05 04:37 UTC by spaceforce-dev

**Add space for MANTRA DAO**  
  
Etherscan: https://etherscan.io/address/0x2baecdf43734f22fd5c152db08e3c27233f0c7d2
CoinGecko: https://www.coingecko.com/en/coins/mantra-dao
Website: https://www.mantradao.com
Twitter: https://twitter.com/mantradao

2020-11-05 07:08 UTC, gokaiorg requested changes
The images file size should not exceed 50KB. Please reduce their weight.

2020-11-05 07:08 UTC, gokaiorg commented on spaces/mantra-dao/index.json
> +  "token": "0x2baEcDf43734F22FD5c152DB08E3C27233F0c7d2",
You will have to remove the skin field. We do not use it anymore. Please refer to the documentation https://docs.snapshot.page/guides/create-a-space#3-space-metadata

2020-11-05 07:10 UTC, gokaiorg commented
Related to https://github.com/snapshot-labs/snapshot.js/pull/29

2020-11-05 07:14 UTC, spaceforce-dev commented
Thanks @gokaiorg 

I cant find where it mentions skins aren't used anymore, can you help point me in the right direction?'

2020-11-05 07:17 UTC, spaceforce-dev commented
Or do i just simply remove skin the line from my index.js

2020-11-05 07:20 UTC, gokaiorg commented
@spaceforce-dev I was talking about the field token sorry!

2020-11-05 08:29 UTC, spaceforce-dev commented
Should have all required updates now 👍

2020-11-09 02:01 UTC, gokaiorg requested changes
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/98492339-1fc7d600-226a-11eb-8705-9231e830effe.png)
![image](https://user-images.githubusercontent.com/8545464/98492349-25bdb700-226a-11eb-829e-5030c1ba119d.png)

2020-11-09 03:11 UTC, spaceforce-dev commented
OOps thanks for spotting that.

Has this change i just pushed made it readable? i want the text to be light ie white

2020-11-09 03:13 UTC, spaceforce-dev commented
<img width="320" alt="Screen Shot 2020-11-09 at 2 12 51 pm" src="https://user-images.githubusercontent.com/71380821/98496400-ae058180-2295-11eb-9139-9031807ec364.png">

2020-11-09 03:13 UTC, spaceforce-dev commented
i'm trying to get it to look similar to this mockup.

2020-11-09 13:59 UTC, gokaiorg approved these changes

2020-11-09 13:59 UTC, merged