Dawn
snapshot-labs/snapshot-spaces pull request #497
Opened 2020-11-16 09:54 UTC by miohtama

Add space for Dawn
  
Etherscan: https://etherscan.io/token/0x580c8520deda0a441522aeae0f9f7a5f29629afa
CoinGecko: https://www.coingecko.com/en/coins/dawn-protocol
Website: https://dawn.org/
Twitter: https://twitter.com/DawnProtocol

2020-11-16 11:54 UTC, gokaiorg requested changes

2020-11-16 11:54 UTC, gokaiorg commented on skins/dawn.scss
> +    --bg-color: #f9fafb;
Please use only theme variables. No extra custom styles are allowed.

2020-11-16 11:54 UTC, gokaiorg commented on spaces/domains.json
> +  "governance.dawn.org": "dawn"
You miss a comma.
```suggestion
  "governance.dawn.org": "dawn",
```

2020-11-16 11:54 UTC, gokaiorg commented on spaces/dawn/index.json
> +  "skin": "dawn",
You will need to add domain field to make your subdomain work.
```suggestion
  "skin": "dawn",
  "domain": "governance.dawn.org",
```

2020-11-16 16:48 UTC, miohtama commented on skins/dawn.scss
> +    --bg-color: #f9fafb;
Did a copy from existing `aave.scss` where they had similar styles, so removing.

2020-11-16 16:48 UTC, miohtama commented on spaces/dawn/index.json
> +  "skin": "dawn",
Thank you!

2020-11-16 16:58 UTC, miohtama commented on skins/dawn.scss
> +    --bg-color: #f9fafb;
Removed any styles now.

2020-11-16 16:59 UTC, miohtama commented on spaces/domains.json
> +  "governance.dawn.org": "dawn"
Fixed.

2020-11-16 16:59 UTC, miohtama commented on spaces/dawn/index.json
> +  "skin": "dawn",
Added domain - not sure in `domains.json` is also needed.

2020-11-17 01:48 UTC, gokaiorg requested changes
The images file size should not exceed 50KB. Please reduce their weight.
You will miss logo.png.

2020-11-19 12:22 UTC, miohtama commented
> The images file size should not exceed 50KB. Please reduce their weight.
> You will miss logo.png.

Reduced space.png size with palettized PNG.

Also added `logo.png` (same as space.png) - not sure what is difference between these two.

2020-11-20 01:26 UTC, gokaiorg approved these changes

2020-11-20 01:30 UTC, merged