Add TRS space
snapshot-labs/snapshot-spaces pull request #523
Opened 2020-11-20 19:20 UTC by Ultrabitch

**Add space for TraderSquare**  
  
Etherscan: https://etherscan.io/token/0x1ef4d930097d30689b16945aa8286c62ce7f75df  
CoinGecko: https://www.coingecko.com/en/coins/tradersquare 
Website: https://www.trader-square.fr/team
Twitter: https://twitter.com/tradersquareoff

2020-11-21 03:09 UTC, gokaiorg requested changes
Space folder should be in lowercase `spaces/tradersquare/index.json`
Do not edit `example` space directory.

2020-11-21 03:09 UTC, gokaiorg commented on spaces/TraderSquare/index.json
> +  "skin": "example",
If you use the default theme you will have to remove the skin field.

2020-11-21 07:51 UTC, Ultrabitch commented on spaces/TraderSquare/index.json
> +  "skin": "example",
Thank you for your help

2020-11-21 09:13 UTC, Ultrabitch commented on spaces/TraderSquare/index.json
> +  "skin": "example",
Ok that's it. I restored initial exemple files, I added new skin"tradersquare.scss" and I update "index.json" with corresponding skin.
Thanks

2020-11-21 20:22 UTC, bonustrack commented
@Ultrabitch It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

2020-11-23 13:14 UTC, Ultrabitch commented
Hey,
I've made the requested changes here, could you please update this PR ?

2020-11-25 10:53 UTC, Ultrabitch commented
@gokaiorg done !

2020-11-25 12:33 UTC, gokaiorg commented
@Ultrabitch We have made a major update. You should now use ENS and IPFS method to create your space. Here is the guide: https://docs.snapshot.page/guides/create-a-space. I'm closing this PR for now, you will need to open a new one to add your space images. Thank you.

2020-11-25 12:33 UTC, closed without merging