update FinNexus space strategy and added skin
snapshot-labs/snapshot-spaces pull request #543
Opened 2020-11-25 02:10 UTC by Jeffqg123

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

2020-11-25 12:58 UTC, gokaiorg approved these changes

2020-11-25 15:10 UTC, gokaiorg requested changes

2020-11-25 15:10 UTC, gokaiorg commented on spaces/finnexus/index.json
> +  "domain": "vote.finnexus.io",
You will need to add your custom domain in this file https://github.com/snapshot-labs/snapshot-spaces/blob/master/spaces/domains.json.

2020-11-26 04:18 UTC, gokaiorg approved these changes

2020-11-26 04:18 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.finnexus.io": "fnx"
This value should be your space directory name.
```suggestion
  "vote.finnexus.io": "finnexus"
```

2020-11-26 04:35 UTC, merged

2020-11-26 07:46 UTC, Jeffqg123 commented on spaces/domains.json
> +  "vote.finnexus.io": "fnx"
This pull request is merged ,right? 
And the modification take affect now?