Add ESD Space
snapshot-labs/snapshot-spaces pull request #554
Opened 2020-11-26 16:02 UTC by l3wi

As title, add ESD space.

2020-11-27 04:06 UTC, gokaiorg requested changes
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin, do not forget to change your space directory name with your ENS domain name `spaces/example.eth/logo.png`)

2020-11-27 11:01 UTC, l3wi commented
@gokaiorg See the requested changes.

2020-11-28 01:38 UTC, gokaiorg approved these changes

2020-11-29 12:27 UTC, l3wi commented
Added custom URL

2020-11-30 05:19 UTC, gokaiorg approved these changes

2020-11-30 05:35 UTC, merged