Add GDS space
snapshot-labs/snapshot-spaces pull request #565
Opened 2020-11-30 07:27 UTC by nftgoddess

Please add our project to snapshot! Thanks in advanced!

2020-11-30 07:45 UTC, nftgoddess commented
Please help to review this @gokaiorg

2020-12-01 01:46 UTC, gokaiorg requested changes
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

2020-12-04 07:43 UTC, nftgoddess commented
@gokaiorg we complete our ens registration, and our custom domain is at vote.nftgoddess.art

2020-12-04 08:42 UTC, gokaiorg requested changes
@nftgoddess I can't find your `nftgoddess.eth` space. Did you already created it?
The images file size should not exceed 50KB. Please reduce their weight.
Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.

2020-12-04 08:42 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.nftgoddess.art": "nftgoddess",
Your domain field value should be similar to your space directory `"my.custom.domain": "my-space.eth"`.
```suggestion
  "vote.nftgoddess.art": "nftgoddess.eth",
```

2020-12-04 08:42 UTC, gokaiorg commented on spaces/nftgoddess/index.json
> +
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2020-12-06 20:06 UTC, nftgoddess commented on spaces/domains.json
> +  "vote.nftgoddess.art": "nftgoddess",
I've just update the correct ens.

2020-12-06 20:07 UTC, nftgoddess commented on spaces/nftgoddess/index.json
> +
I've deleted this file.

2020-12-07 02:27 UTC, gokaiorg requested changes
- Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.
- The images file size should not exceed 50KB. Please reduce their weight.

2020-12-09 19:30 UTC, nftgoddess commented
> * Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.
> * The images file size should not exceed 50KB. Please reduce their weight.

I've just complied with these requirement.

2020-12-10 01:56 UTC, gokaiorg approved these changes

2020-12-10 02:20 UTC, merged