Update domains.json
snapshot-labs/snapshot-spaces pull request #568
Opened 2020-12-01 06:40 UTC by wwggyy2002

Add Space ushiled

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

2020-12-02 02:26 UTC, gokaiorg approved these changes

2020-12-02 02:29 UTC, gokaiorg commented
@wwggyy2002 Did you already create your ushiled.eth space, i cannot find it?

2020-12-04 03:24 UTC, wwggyy2002 commented
Sorry,my mistake,I write wrong space name.

2020-12-04 03:26 UTC, gokaiorg commented
@wwggyy2002 Could you send me a link to your space? I still can't find `ltcapital.eth` space.

2020-12-04 03:27 UTC, gokaiorg requested changes

2020-12-04 03:27 UTC, gokaiorg commented on spaces/domains.json
> +   "mtrg.meter.io": "meter-mainnet.eth",
Beware of side effects.
```suggestion
  "mtrg.meter.io": "meter-mainnet.eth",
```

2020-12-09 03:35 UTC, wwggyy2002 commented
here is our space
https://snapshot.page/#/ltcapital.eth

2020-12-09 03:35 UTC, wwggyy2002 commented
> @wwggyy2002 Could you send me a link to your space? I still can't find `ltcapital.eth` space.

https://snapshot.page/#/ltcapital.eth

2020-12-10 02:23 UTC, gokaiorg requested changes
There is a conflict in your PR, can you resolve it?

2020-12-18 23:14 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-12-18 23:14 UTC, closed without merging