Add BBRA.eth space (ENS)
snapshot-labs/snapshot-spaces pull request #570
Opened 2020-12-01 12:48 UTC by boobank

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

2020-12-01 13:12 UTC, bonustrack commented on skins/bbra.scss
> +  --primary-color: rgb(173 48 48);
```suggestion
  --primary-color: rgb(173, 48, 48);
```

2020-12-01 13:12 UTC, bonustrack commented on skins/bbra.scss
> +  .border-md {
You shouldn't change the style of the css classes, #topnav is the only exception.

2020-12-01 15:33 UTC, boobank commented on skins/bbra.scss
> +  .border-md {
Shouldn't or mustn't? Happy to take the chances if you guys allow!

2020-12-02 02:33 UTC, gokaiorg requested changes
Please use only theme variables. No extra custom styles are allowed.

2020-12-03 01:29 UTC, gokaiorg commented
There is a conflict in your PR, can you resolve it?

2020-12-10 02:24 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2020-12-10 02:24 UTC, closed without merging