Add Midas Space
snapshot-labs/snapshot-spaces pull request #582
Opened 2020-12-03 06:05 UTC by midas-defi

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

2020-12-03 12:45 UTC, gokaiorg requested changes
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

2020-12-05 09:20 UTC, midas-defi commented
I want to register a logo.

2020-12-05 12:33 UTC, gokaiorg requested changes
Delete also your `spaces/midas-defi/images.png` to keep only `spaces/midas-defi.eth/images.png`.

2020-12-05 12:33 UTC, gokaiorg commented on spaces/midas-defi/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2020-12-05 12:34 UTC, gokaiorg approved these changes

2020-12-06 09:51 UTC, midas-defi commented
@gokaiorg index.json delete. Please review again.

2020-12-06 09:58 UTC, gokaiorg commented
> Delete also your `spaces/midas-defi/images.png` to keep only `spaces/midas-defi.eth/images.png`.

@midas-defi You still need to delete 2 images. Thank you.

2020-12-06 14:40 UTC, midas-defi commented
@gokaiorg Please review it again Sorry!

2020-12-10 02:28 UTC, gokaiorg approved these changes
Sorry for the delay i didn’t see your update!

2020-12-10 02:36 UTC, merged