add BT spaces
snapshot-labs/snapshot-spaces pull request #589
Opened 2020-12-04 02:49 UTC by btdotfinance

Github:https://github.com/btdotfinance

Twitter:https://Twitter.com/btdotfinance

Medium:https://Medium.com/@btfinance

Discord:https://discord.gg/Z3aDmTefw6

Forum:https://gov.bt.finance

Vote:https://vote.bt.finance

2020-12-04 02:51 UTC, gokaiorg requested changes
It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)

2020-12-04 02:57 UTC, btdotfinance commented
ENS and IPFS is ok,now update logo

2020-12-04 03:35 UTC, gokaiorg requested changes
Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.

2020-12-04 03:35 UTC, gokaiorg commented on skins/bt.scss
> +.yearn {
The css selector should similar to the skin name.
```suggestion
.bt {
```

2020-12-04 03:35 UTC, gokaiorg commented on spaces/BT.Finance/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2020-12-04 03:35 UTC, gokaiorg commented on spaces/domains.json
>  }
There is a conflict in your PR, can you resolve it?

2020-12-04 03:35 UTC, gokaiorg commented on spaces/bt/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2020-12-04 03:37 UTC, gokaiorg commented on skins/bt.scss
> +.yearn {
You could also remove skin.scss and set yearn for skin in your space settings.

2020-12-04 03:41 UTC, btdotfinance commented
use ENS and IFPS,Index.json and skin have been removed

2020-12-04 03:44 UTC, btdotfinance commented on skins/bt.scss
> +.yearn {
> Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.

ok,Has been renamed

2020-12-04 03:48 UTC, btdotfinance commented on spaces/domains.json
>  }
of course

2020-12-07 01:28 UTC, btdotfinance commented
Please take a look at what else needs to be modified?

2020-12-07 02:34 UTC, gokaiorg requested changes
Please have a look on this page https://github.com/snapshot-labs/snapshot-spaces/pull/589/files
You have 2 spaces, you will want to keep only the `btfinance.eth` one.

**Delete files:**
1. spaces/BT.Finance/index.json
2. spaces/BT.Finance/logo.png
3. spaces/BT.Finance/space.png

**Conflict**
You will also need to update your local fork to get the last version of `spaces/domains.json` and then resolve the conflict.

2020-12-07 05:59 UTC, btdotfinance commented
already updated

2020-12-07 07:23 UTC, gokaiorg requested changes
There is a conflict in your PR, can you resolve it?

2020-12-07 07:23 UTC, gokaiorg commented on spaces/domains.json
>    "vote.zlot.finance": "zlot",
When you added your domain, you duplicated 2 lines in domain.json
```suggestion
  "vote.bt.finance": "btfinance.eth",
  "vote.zlot.finance": "zlot",
```

2020-12-07 07:23 UTC, gokaiorg commented on spaces/domains.json
>    "gov.kp2r.network": "keep2r.eth",
When you added your domain, you duplicated 2 lines in domain.json
```suggestion
  "gov.kp2r.network": "keep2r.eth",
```

2020-12-07 07:53 UTC, btdotfinance commented
It has been modified

2020-12-07 10:13 UTC, gokaiorg approved these changes

2020-12-07 10:15 UTC, merged