Update the header color for badger.scss
snapshot-labs/snapshot-spaces pull request #599
Opened 2020-12-05 19:33 UTC by mitche50

2020-12-06 02:28 UTC, gokaiorg approved these changes

2020-12-06 02:29 UTC, gokaiorg commented
There is a conflict in your PR, can you resolve it?

2020-12-18 23:08 UTC, gokaiorg requested changes

2020-12-18 23:08 UTC, gokaiorg commented on skins/badger.scss
>  }
Please use only theme variables. No extra custom styles are allowed except on #topnav. Thank you.

2020-12-18 23:22 UTC, mitche50 commented
Is there any way to make the active button show a different color? Right now it’s impossible to see which button is selected.

Sent from my iPhone

> On Dec 18, 2020, at 6:08 PM, Gokai <notifications@github.com> wrote:
> 
> ﻿
> @gokaiorg requested changes on this pull request.
> 
> In skins/badger.scss:
> 
> > +.button--active {
> +  color: #fff !important;
> +  background-color: var(--primary-color) !important;
>  }
> Please use only theme variables. No extra custom styles are allowed except on #topnav. Thank you.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-18 23:28 UTC, gokaiorg commented
I think your best way is to change the border-color, make sure it's not the same as the link-color. Tell me if you can do something in this way, thank you.

2020-12-19 01:41 UTC, mitche50 commented
Updated to modify link color and remove the extra custom style @gokaiorg

2020-12-20 01:42 UTC, gokaiorg approved these changes

2020-12-20 01:43 UTC, merged