Add DSGN space
snapshot-labs/snapshot-spaces pull request #611
Opened 2020-12-08 16:09 UTC by blokku-chan

2020-12-08 17:11 UTC, bonustrack commented
@blokku-chan Do you know that you can use the domain wearedesign.xyz directly on ENS and on Snapshot instead of the .eth? Have a look here: https://snapshot.page/#/wearedesign.xyz/settings

2020-12-08 17:14 UTC, blokku-chan commented
@bonustrack Hey there, that's interesting, I didn't realise that. However, the owner of the site is using wearedesign.xyz as a marketing/informational site. I'm a community member just helping out based on his request, so I'd say let's stick with the .eth domain. Thanks!

2020-12-09 01:28 UTC, gokaiorg requested changes
I can't find your `wearedesign.eth` space, did you create it already?

2020-12-09 01:28 UTC, gokaiorg commented on spaces/wearedesign.eth/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2020-12-09 10:48 UTC, blokku-chan commented
@gokaiorg Hey, is this what you were looking for? 

https://app.ens.domains/name/wearedesign.eth
https://snapshot.page/#/wearedesign.eth/

Please advise

2020-12-09 10:49 UTC, blokku-chan commented on spaces/wearedesign.eth/index.json
> +}
@gokaiorg Huh... I was following the steps in the GitHub, sure I'd take it out

2020-12-09 11:04 UTC, blokku-chan commented on spaces/wearedesign.eth/index.json
> +}
@gokaiorg I've removed the index.json now

2020-12-10 02:03 UTC, gokaiorg commented
@blokku-chan Yes, i still can't find your space on https://snapshot.page/#/wearedesign.eth/ url.

2020-12-11 07:53 UTC, blokku-chan commented
@gokaiorg Thanks for the help, apparently the owner is yet to add the settings. I will let you know when that is done! 🙏

2020-12-12 21:47 UTC, nickcamsmith commented
@gokaiorg have updated the settings. Lmk if you need anything further.

2020-12-14 00:28 UTC, gokaiorg approved these changes

2020-12-14 00:53 UTC, merged