Add_KFI
snapshot-labs/snapshot-spaces pull request #644
Opened 2020-12-15 09:21 UTC by solproc

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

2020-12-16 01:18 UTC, gokaiorg approved these changes

2020-12-16 01:33 UTC, gokaiorg commented
There is a conflict in your PR, can you resolve it?

2020-12-18 01:08 UTC, gokaiorg requested changes

2020-12-18 01:08 UTC, gokaiorg commented on spaces/domains.json
>    "vote.coverprotocol.com": "cover"
You miss a comma.
```suggestion
  "vote.coverprotocol.com": "cover",
```

2020-12-18 18:49 UTC, solproc reviewed
it should be ok now.

2020-12-18 23:06 UTC, gokaiorg approved these changes

2020-12-18 23:06 UTC, merged