Add SPDR space
snapshot-labs/snapshot-spaces pull request #674
Opened 2020-12-22 16:00 UTC by flisko

Created a space via ENS.

2020-12-22 23:18 UTC, gokaiorg requested changes

2020-12-22 23:18 UTC, gokaiorg commented on skins/spiderdao.scss
> +.example {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.spiderdao {
```

2020-12-22 23:21 UTC, gokaiorg commented
There is a conflict in your PR, can you resolve it?

2020-12-23 08:25 UTC, flisko commented
> There is a conflict in your PR, can you resolve it?

Resolved.

2020-12-23 14:38 UTC, flisko commented
@gokaiorg Please check.

2020-12-24 02:02 UTC, gokaiorg approved these changes

2020-12-24 02:03 UTC, merged