add ndx.eth
snapshot-labs/snapshot-spaces pull request #712
Opened 2021-01-06 16:49 UTC by d1ll0n

Add NDX logo, skin, space, and domain

2021-01-07 02:28 UTC, gokaiorg requested changes

2021-01-07 02:28 UTC, gokaiorg commented on skins/indexed.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/103843576-ac580e80-50ca-11eb-9d5f-447154f7296a.png)

2021-01-07 12:50 UTC, d1ll0n commented on skins/indexed.scss
> +}
Thank you, updated.

2021-01-08 02:23 UTC, gokaiorg approved these changes

2021-01-08 02:32 UTC, merged