Add BarnBridge Snapshot config
snapshot-labs/snapshot-spaces pull request #745
Opened 2021-01-13 16:35 UTC by bogdangheorghe

2021-01-13 16:36 UTC, rizedr approved these changes

2021-01-14 00:39 UTC, gokaiorg requested changes
Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.

2021-01-14 12:11 UTC, gokaiorg commented
The spaces/domains.json file has been updated and there is a conflict in your PR, can you resolve it?

2021-01-14 12:17 UTC, bogdangheorghe commented
sorry @gokaiorg should be good now

2021-01-14 12:22 UTC, gokaiorg approved these changes

2021-01-14 12:22 UTC, merged