ADD flexusd.eth Space
snapshot-labs/snapshot-spaces pull request #796
Opened 2021-01-22 09:40 UTC by c01nfl3x

Change to add flexusd.eth space

2021-01-22 09:45 UTC, gokaiorg requested changes

2021-01-22 09:45 UTC, gokaiorg commented on spaces/aliases.json
>  }
You need to edit this file only if you migrate an existing space to a space created with ENS. For a new space, just follow this documentation https://docs.snapshot.page/guides/create-a-space

2021-01-22 09:48 UTC, c01nfl3x commented on spaces/aliases.json
>  }
Thanks @gokaiorg . That was done already but when I go to created space page it shows a blank screen.

2021-01-22 09:52 UTC, gokaiorg commented on spaces/aliases.json
>  }
Do you have access to this page and if so, did you fill in the required fields? https://snapshot.page/#/flexusd.eth/settings

2021-01-22 09:55 UTC, c01nfl3x commented on spaces/aliases.json
>  }
Yes, I left out without filling only Members and Filters, the rest is filled.

2021-01-24 05:30 UTC, gokaiorg requested changes
Your space is displayed but it's not a space migration, use your PR to add your logos or your sub-domain but you have to delete the aliases .json files.

2021-01-25 11:18 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.
If you want to add avatars please follow this link https://docs.snapshot.page/guides/add-avatars

2021-01-25 11:18 UTC, closed without merging