Updating AirSwap and adding Rinkeby space
snapshot-labs/snapshot-spaces pull request #807
Opened 2021-01-25 23:21 UTC by dmosites

2021-01-26 01:12 UTC, gokaiorg requested changes
- It's now possible to create and edit a space without doing pull requests but using ENS and IPFS instead. Could you use this new method to create your space? Here is the guide: https://docs.snapshot.page/guides/create-a-space (you can keep your PR for add the images and skin)
- Could you create a PR to edit Airswap space and create the new one with ENS?
- You also should migrate your Airswap space on ENS if possible! Thank you.

2021-01-26 09:23 UTC, dmosites commented
Thanks @gokaiorg I've configured ENS content records for `vote.airswap.eth` and `vote-rinkeby.airswap.eth` and updated the entries in `domains.json` and `aliases.json`. Let me know how it looks thank you!

2021-01-26 11:17 UTC, gokaiorg requested changes
- @dmosites When you create a space with ENS, you should have an url looks like https://snapshot.page/#/vote.airswap.eth
- Please follow this doc to get more info to complete it https://docs.snapshot.page/guides/create-a-space
- Your space directory should be named `spaces/vote.airswap.eth/logo.png` instead of `spaces/airswap/logo.png` in this case.

2021-01-26 11:17 UTC, gokaiorg commented on spaces/aliases.json
> +  "airswap-rinkeby": "vote-rinkeby.airswap.eth",
Add a line here only if you have an existing space to migrate, airswap-rinkeby should not be there.
```suggestion
```

2021-01-28 10:31 UTC, dmosites commented
Thanks @gokaiorg should be good to go. I've reviewed the documentation and think we've got it right.

2021-01-28 11:13 UTC, gokaiorg approved these changes
@dmosites Everything looks good to me :) 

Just do you know why your https://snapshot.page/#/vote.airswap.eth and https://snapshot.page/#/vote-rinkeby.airswap.eth spaces doesn’t loads?

Have you filled out all the required fields and added a strategy?

2021-01-28 15:38 UTC, dmosites commented
Awesome. Yup those have been updated, I'll separately request the existing proposals to be migrated over on Discord.

Thanks @gokaiorg!

2021-01-29 01:53 UTC, gokaiorg commented
> Awesome. Yup those have been updated, I'll separately request the existing proposals to be migrated over on Discord.
> 
> Thanks @gokaiorg!

Great @dmosites! The migrated space https://snapshot.page/#/vote.airswap.eth doesn’t look to be loaded. Could you have a look on it before we merge an do the migration process? Thank you 😊

2021-01-30 11:35 UTC, merged