Add AngelDAO theme
snapshot-labs/snapshot-spaces pull request #832
Opened 2021-02-01 20:42 UTC by meirbank

**If you want to create a space follow this guide**

https://docs.snapshot.page/guides/create-a-space

2021-02-02 00:59 UTC, gokaiorg requested changes
I can't find your https://snapshot.page/#/angeldao.eth space, did you create it already?

2021-02-02 00:59 UTC, gokaiorg commented on skins/angeldao.scss
> +.benchmark {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.angeldao {
```

2021-02-02 22:09 UTC, meirbank commented
> I can't find your https://snapshot.page/#/angeldao.eth space, did you create it already?

No we will create it soon, need to get our multi sig wallet ready. Thanks for the fix.

2021-02-04 01:36 UTC, gokaiorg commented
@meirbank Please let me know when your new space is live then i will merge this PR. Thank you.

2021-02-04 17:08 UTC, meirbank commented
Created, https://snapshot.page/#/AngelDAO.eth

Thanks

2021-02-04 22:47 UTC, gokaiorg commented
@bonustrack Does an ENS with uppercase letters need a folder name for the space with uppercase letters too? Thank you.

2021-02-05 07:02 UTC, bonustrack commented
@meirbank @gokaiorg Hi sorry but both the folder and the ENS domain should be lowercased.

2021-02-05 16:01 UTC, meirbank commented
Ok we will have to make a new snapshot page soon then I guess

2021-02-14 13:18 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-02-14 13:18 UTC, closed without merging