Bamboo spaces
snapshot-labs/snapshot-spaces pull request #887
Opened 2021-02-19 07:56 UTC by Ibai-NexxyoLabs

Added custom skin and custom domain for BambooDeFi

2021-02-19 08:19 UTC, gokaiorg requested changes
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy.
https://snapshot.page/#/bamboodefi.eth

2021-02-19 08:19 UTC, gokaiorg commented on spaces/domains.json
> +  "bamboodefi.com": "bamboodefi.eth"
Are you sure you want to point your Snapshot space to your main domain and not create a sub-domain instead? For example:
```suggestion
  "vote.bamboodefi.com": "bamboodefi.eth"
```

2021-02-19 08:19 UTC, gokaiorg commented on skins/bamboodefi.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/108477514-e4f02800-72c5-11eb-93d3-bbbb4704237b.png)

2021-02-19 08:41 UTC, Ibai-NexxyoLabs commented on spaces/domains.json
> +  "bamboodefi.com": "bamboodefi.eth"
Yes, vote.bamboodefi.com is good.

2021-02-19 08:48 UTC, Ibai-NexxyoLabs commented on skins/bamboodefi.scss
> +}
The link color attribute has been changed

2021-02-23 02:13 UTC, gokaiorg requested changes
Your space still not loading. Do you need some help to create it?

2021-02-23 02:13 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.bamboodefi.com": "bamboodefi.eth"
You miss a comma at the end of the line.
```suggestion
  "vote.bamboodefi.com": "bamboodefi.eth",
```

2021-03-01 09:15 UTC, gokaiorg commented
@Ibai-NexxyoLabs You may miss to set a name before saving your space settings, cause your space still not loading properly and you have a name error in the console.
![image](https://user-images.githubusercontent.com/8545464/109476312-5b9cda80-7aa9-11eb-893f-7dc4ac7da45a.png)

2021-03-01 09:16 UTC, gokaiorg requested changes
.

2021-03-02 01:29 UTC, gokaiorg requested changes

2021-03-02 01:29 UTC, gokaiorg commented on skins/bamboodefi.scss
> +}
The colors used in your skin make the interface unreadable, please change with others or remove the skin to use the default theme.
![image](https://user-images.githubusercontent.com/8545464/109582813-67cc7a80-7b31-11eb-9482-0711c88947f0.png)

2021-03-02 08:58 UTC, Ibai-NexxyoLabs reviewed
The changes have been added

2021-03-02 09:00 UTC, Ibai-NexxyoLabs reviewed
CSS styles fixed

2021-03-02 09:00 UTC, gokaiorg approved these changes

2021-03-02 09:00 UTC, merged