Migrate Tokenlon space
snapshot-labs/snapshot-spaces pull request #901
Opened 2021-02-25 03:44 UTC by BenjaminLu

Tokenlon team wanna migrate space to `tokenlon.eth`. So we could submit a `tokenlon` strategy later.

- [ ] Add images for your space
- [ ] Add custom domain for your space
- [x] Add alias for migrate your space
- [ ] Add or edit a skin
- [ ] Edit your space with GitHub? It's recommended to migrate to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) https://docs.snapshot.page/spaces/create

2021-02-25 04:11 UTC, gokaiorg requested changes
- I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.page/#/tokenlon.eth
- Your space name directory should be similar to your ENS. Follow this example `spaces/my-space.eth/logo.png`.

2021-02-25 04:35 UTC, BenjaminLu commented
Thanks for reminding me. `tokenlon` folder have been renamed to `tokenlon.eth`

2021-02-28 02:25 UTC, BenjaminLu commented
https://app.ens.domains/name/tokenlon.eth
It should work now.

2021-03-01 04:28 UTC, gokaiorg approved these changes

2021-03-01 04:29 UTC, merged