Update Yearn space
snapshot-labs/snapshot-spaces pull request #907
Opened 2021-02-26 13:43 UTC by fameal

#### Hi! What is your PR about?

- [ ] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- [ ] Edit your space with GitHub? It's recommended to migrate to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) https://docs.snapshot.page/spaces/create

2021-02-26 14:30 UTC, gokaiorg requested changes

2021-02-26 14:30 UTC, gokaiorg commented on skins/yearn.scss
> +  }
Please use only theme variables. No extra custom styles are allowed. This would make it difficult to update the structure of the site.

2021-03-01 10:17 UTC, fameal commented on skins/yearn.scss
> +  }
not even #topnav?

2021-03-01 10:18 UTC, bonustrack commented on skins/yearn.scss
> +  }
@fameal Topnav is fine

2021-03-01 10:22 UTC, fameal commented
Thanks @bonustrack! I've removed #app customization and the font import

2021-03-01 10:23 UTC, merged