Add TCR Space
snapshot-labs/snapshot-spaces pull request #920
Opened 2021-03-01 07:28 UTC by tetther1122

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- [ ] Edit your space with GitHub? It's recommended to migrate to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) https://docs.snapshot.page/spaces/create

2021-03-01 09:19 UTC, gokaiorg requested changes
I can't find your new space. Please make sure that you have filled in all required fields and added a strategy. https://snapshot.page/#/tracer.eth
Your space name directory should be similar to your ENS. Follow this example `spaces/tracer.eth/logo.png`.

2021-03-03 02:19 UTC, gokaiorg approved these changes

2021-03-03 02:19 UTC, gokaiorg commented on skins/tracer.scss
> +}
Your validate button seems disabled, do you want to change the style?
![image](https://user-images.githubusercontent.com/8545464/109742388-84d07e80-7c01-11eb-80f1-dd95c844eb21.png)
![image](https://user-images.githubusercontent.com/8545464/109742254-55ba0d00-7c01-11eb-9c3b-8d06bb05b8ac.png)

2021-03-03 02:36 UTC, tetther1122 commented on skins/tracer.scss
> +}
I had a quick look locally but I think that should work

2021-03-03 02:40 UTC, merged