ICHI.farm logo update
snapshot-labs/snapshot-spaces pull request #928
Opened 2021-03-03 17:51 UTC by DTal621

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- [ ] Edit your space with GitHub? It's recommended to migrate to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) https://docs.snapshot.page/spaces/create

2021-03-03 17:58 UTC, DTal621 commented
just updated to square format

2021-03-04 02:51 UTC, gokaiorg requested changes
Your space name directory should be similar to your ENS. Follow this example `spaces/ichi.eth/logo.png`. https://snapshot.page/#/ichi.eth

2021-03-04 07:08 UTC, DTal621 commented
@gokaiorg thanks for the guidance - it has been updated. Let me know if all looks good or if there are any other changes needed. If it looks good then please merge.

2021-03-05 01:52 UTC, gokaiorg approved these changes

2021-03-05 01:52 UTC, merged