Add custom domain to riseprotocol.eth
snapshot-labs/snapshot-spaces pull request #934
Opened 2021-03-05 15:52 UTC by RiseProtocol

#### Hi! What is your PR about?

- [] Add images for your space
- [X ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-06 03:00 UTC, gokaiorg requested changes

2021-03-06 03:00 UTC, gokaiorg commented on spaces/domains.json
> +  "riseprotocol.io/governance': "riseprotocol.eth"
A comma is missing at the end of the line above your sub-domain.
```suggestion
  "vote.cndy.finance": "candyfinance.eth",
  "riseprotocol.io/governance': "riseprotocol.eth"
```

2021-03-06 16:54 UTC, RiseProtocol reviewed
Added comma. 
Changed custom domain to "gov.riseprotocol.io"

2021-03-06 16:57 UTC, gokaiorg requested changes

2021-03-06 16:57 UTC, gokaiorg commented on spaces/domains.json
> +  "gov.riseprotocol.io': "riseprotocol.eth"
You must replace the single quote with a double quote.
```suggestion
  "gov.riseprotocol.io": "riseprotocol.eth"
```

2021-03-06 17:05 UTC, RiseProtocol reviewed
Edited to include double quotes.

2021-03-06 23:37 UTC, RiseProtocol commented
Please review my changes and merge the branch. Thanks!

2021-03-07 03:29 UTC, gokaiorg approved these changes

2021-03-07 03:30 UTC, gokaiorg commented
The `domains.json` file has been updated since your last commit and there is a conflict in your PR, can you resolve it?

2021-03-08 16:48 UTC, RiseProtocol reviewed
Copied over latest domain.json file and added custom riseprotocol.eth domain.

2021-03-09 01:20 UTC, gokaiorg commented
There is still a conflict, can you try the following commands? Thank you
`git remote add master https://github.com/snapshot-labs/snapshot-spaces.git`
`git fetch master`
`git checkout master`
`git merge master/master`

2021-03-15 02:15 UTC, gokaiorg commented
Closing this PR for now, feel free to open it again once you've done the changes.

2021-03-15 02:15 UTC, closed without merging