added bears.finance (fbear.eth)
snapshot-labs/snapshot-spaces pull request #937
Opened 2021-03-06 17:26 UTC by MindfulMe

#### Hi! What is your PR about?

- [x] Add images for your space
- [x] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-06 17:28 UTC, MindfulMe commented
@gokaiorg review please

2021-03-06 17:34 UTC, MindfulMe commented
DNS record for custom domain is already added and our space is listed on snapshot.page as Bears as well
<img width="1178" alt="Screenshot 2021-03-06 at 19 33 51" src="https://user-images.githubusercontent.com/26275425/110215513-e66b4400-7eb2-11eb-8530-b8cfb3200ce0.png">
 <img width="1017" alt="Screenshot 2021-03-06 at 19 31 49" src="https://user-images.githubusercontent.com/26275425/110215464-9b513100-7eb2-11eb-899a-98f46f4a53e8.png">

2021-03-06 17:36 UTC, MindfulMe commented on spaces/fbear.eth/index.json
> +  "members": [
Will new members attached automatically? I mean whether someone else can create a proposal? We need other people to create proposals too not only those 2 members

2021-03-07 03:35 UTC, gokaiorg requested changes

2021-03-07 03:35 UTC, gokaiorg commented on spaces/fbear.eth/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-03-10 10:38 UTC, MindfulMe commented on spaces/fbear.eth/index.json
> +}
done

2021-03-10 10:39 UTC, MindfulMe reviewed
done

2021-03-10 12:39 UTC, gokaiorg requested changes

2021-03-10 12:39 UTC, gokaiorg commented on spaces/domains.json
> +  "vote.bears.finance":"fbear.eth",
Could you just add a space here please? Thank you 😊 
```suggestion
  "vote.bears.finance": "fbear.eth",
```

2021-03-14 17:37 UTC, MindfulMe commented on spaces/domains.json
> +  "vote.bears.finance":"fbear.eth",
done

2021-03-14 17:38 UTC, MindfulMe commented
Anything else to update?

2021-03-15 02:05 UTC, gokaiorg approved these changes

2021-03-15 02:05 UTC, merged