Fixing logo, adding skin and index file
snapshot-labs/snapshot-spaces pull request #939
Opened 2021-03-07 01:21 UTC by xyz-ctrl

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [x] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-07 03:45 UTC, gokaiorg requested changes
You may want also add a logo.png image.

2021-03-07 03:45 UTC, gokaiorg commented on spaces/visor.eth/index.json
> +}
Since we use ENS and IFPS, every datas are sets in your space settings, you shouldn’t add index.json file. Please remove it.

2021-03-07 03:45 UTC, gokaiorg commented on skins/visor.scss
> +}
Your submit button may appear to be disabled, maybe you want to change it?
![image](https://user-images.githubusercontent.com/8545464/110228195-d2b2f280-7f31-11eb-8d23-0044217ad9ba.png)

2021-03-07 05:23 UTC, xyz-ctrl commented on skins/visor.scss
> +}
I would like to keep it #ffffff as there isn't really a color that provides great contrast on both

2021-03-07 05:25 UTC, xyz-ctrl commented on spaces/visor.eth/index.json
> +}
removed

2021-03-08 01:40 UTC, gokaiorg approved these changes

2021-03-08 01:46 UTC, merged