Add avatar and change the skin
snapshot-labs/snapshot-spaces pull request #994
Opened 2021-03-16 16:23 UTC by iwanwang-0

#### Hi! What is your PR about?

- [x] Add images for your space
- [ ] Add custom domain for your space
- [ ] Add alias for migrate your space
- [ ] Add or edit a skin
- ~Edit your space with GitHub?~ (deprecated) Please migrate your space to ENS https://docs.snapshot.page/spaces/migrate
- ~Create your space with GitHub~ (deprecated) Create your space with ENS instead https://docs.snapshot.page/spaces/create

2021-03-16 16:46 UTC, iwanwang-0 commented
Hello, I wanna add an avatar and modify the skin. Thanks.

2021-03-17 01:07 UTC, gokaiorg requested changes

2021-03-17 01:07 UTC, gokaiorg commented on skins/shabushabu.scss
> +.amp {
The css selector should similar to the skin file name. `skin.scss` `.skin {}`.
```suggestion
.shabushabu {
```

2021-03-17 03:27 UTC, gokaiorg approved these changes

2021-03-17 03:27 UTC, merged